### ISSUE TITLE
[Problem report] Error: The device is not ready.

### ISSUE THREAD

**Issue by OfficialEsco** [aleksey-hoffman/sigma-file-manager#1]
First issue 😎

## System info:
- **App version**: `1.0.0` 
- **Operating System**: `Win10 Pro N 20H2 19042.928` 

## Problem:
As a WinGet package maintainer i wanted to add Sigma as a package.
The validation process requires to test the package in a VM/Sandbox, the program installed fine, but it cannot find the drives and this error pops up.
![image](https://user-images.githubusercontent.com/15158490/119498847-5aa4dd80-bd66-11eb-8484-70b40ee9b31e.png)

**Comment by aleksey-hoffman** [comment]
Thank you for the problem report!
Man you're quick 😄

**Comment by diwakar1016** [comment]
I have the same issue 
Error: Error: EISDIR, The device is not ready.
 'G:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

**Comment by OfficialEsco** [comment]
Ahh the issue is linked to the CD Drive which i don't have on my main OS
![image](https://user-images.githubusercontent.com/15158490/119500317-f3882880-bd67-11eb-982e-4a9938dc481d.png)

**Comment by diwakar1016** [comment]
![Screenshot 2021-05-25 181814](https://user-images.githubusercontent.com/69196074/119500597-97cc9800-bd85-11eb-9c23-5bf4d2ce191a.png)

It shows no drives found but the UI looks cool though !!!

**Comment by ARAHTHUL** [comment]
First things first, let me thank you and appreciate you effort and work doing this app! Keep up the good work!

Now, as the ones above me, I have this issue about now showing drives:

Error: Error: EISDIR, The device is not ready.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

![25-05-2021 16-15-57-Greenshot](https://user-images.githubusercontent.com/73890037/119504375-6d65e500-bd5b-11eb-8a75-c41f0539c38e.png)

**Comment by aleksey-hoffman** [comment]
Thank you guys, really appreciate your feedback and help.

Can anyone of you code / debug? I don't see this issue on my computers.
- The issue occurs in this file: `src\utils\storageInfo.js` 
- And it's either caused by this function `diskusage.check` or this `sysInfo.blockDevices` function

**Comment by iseeghosts** [comment]
I'm having the same issue Error:
Error: EISDIR, The device is not ready.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)
I don't even have a E: Drive

**Comment by btglr** [comment]
I'm fairly certain it has to do with Network Shares, and possibly also Network Shares that show up as local drives (ie. rclone mounts).
I've tried debugging the app, unfortunately some dependencies can't be met:

```
This dependency was not found:

* fs/promises in ./node_modules/trammel/lib/trammel.js

To install it, you can run: npm install --save fs/promises
```

The GitHub repository fs/promises doesn't exist anymore as it has been deprecated, so it can't be installed at all. You likely haven't encountered the problem because you've been working on the project for a while and still have that package in your `node_modules` folder.

**Comment by mattm-malone** [comment]
@btglr I had a similar issue trying to build. I believe what was happening was I was on npm v6, and it wasn't reading the `package-lock.json` correctly. If you look in the `package-lock.json`, it denotes `"lockfileVersion": 2` which denotes it was generated with npm v7. Clearing my `node_modules`, switching to node v14 and npm v7 fixed this.

**Comment by btglr** [comment]
> 
> 
> @btglr I had a similar issue trying to build. I believe what was happening was I was on npm v6, and it wasn't reading the `package-lock.json` correctly. If you look in the `package-lock.json`, it denotes `"lockfileVersion": 2` which denotes it was generated with npm v7. Clearing my `node_modules` and switching to node v14 and npm v7 fixed this.

You're right, that was the issue. Thanks!

**Comment by aleksey-hoffman** [comment]
Thank you guys. The problem is fixed.
I will release the update today.

**Comment by itsmeshibintmz** [comment]
![image](https://user-images.githubusercontent.com/52344717/119662808-6b7d4e00-be4f-11eb-87e3-bb03b956c996.png)
Looks cool. First time One of my network drives didn't show up. I had to disconnect the network drive. Hope u will fix problems with Network drives in future releases. The UI looks cool. Great work.

**Comment by aleksey-hoffman** [comment]
@itsmeshibintmz thank you brother! The problem with network drives will be fixed soon

**Comment by aleksey-hoffman** [comment]
@itsmeshibintmz by the way, that dinosaur on the image is special - did you already find why?

**Comment by drewb0y** [comment]
Got the same error. I know the issue has been worked on, just wanted to let you know that in my case it was not a network drive but the DVD-RW drive in my laptop. Thanks for all the work!

```
Error: Error: EISDIR, The device is not ready.
 'D:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)
```

**Comment by drewb0y** [comment]
> @itsmeshibintmz by the way, that dinosaur on the image is special - did you already find out why? Take a closer look at it

Is it because it's pixelated?

**Comment by itsmeshibintmz** [comment]
> @itsmeshibintmz by the way, that dinosaur on the image is special - did you already find out why? Take a closer look at it

no. why you say it is so special?

**Comment by OfficialEsco** [comment]
> Got the same error. I know the issue has been worked on, just wanted to let you know that in my case it was not a network drive but the DVD-RW drive in my laptop. Thanks for all the work!

This is affecting all connectable disk readers

> Is it because it's pixelated?

Its just a minigame easteregg 🤐

**Comment by aleksey-hoffman** [comment]
@itsmeshibintmz @drewb0y if you pet it, he will show you something cool
🤐

**Comment by itsmeshibintmz** [comment]
> @itsmeshibintmz @drewb0y if you pet him, he will show you something cool
> 🤐

it's great. I didn't even think of it. great work man. cool idea.

**Comment by aleksey-hoffman** [comment]
@OfficialEsco has this issue been actually resolved in 1.1.0?

**Comment by OfficialEsco** [comment]
It indeed has been fixed, you would have heard if it didn't😁

**Comment by aleksey-hoffman** [comment]
@OfficialEsco good to know. Thank you for testing the app
