### ISSUE TITLE
UI scaling / zoom does not save

### ISSUE THREAD

**Issue by Willy-JL** [aleksey-hoffman/sigma-file-manager#103]
## Problem description:
UI scaling percentage does not save into config, and gets lost after program restart

## Steps to reproduce:

1. Change zoom value in Settings > General > Window Scaling
2. Restart Sigma
3. Zoom back to 100%

## Temporary fix:
I "fixed" my issue by adding this line in %appdata%/Sigma file manager/app storage/settings.json`
```json
"storageData.settings.UIZoomLevel": 0.8
```
`0.8` = `80%` scaling

## System info:
- **App version**: 1.1.0
- **Operating System**: Windows 10

**Comment by aleksey-hoffman** [comment]
Thanks for the report, mate.
I will fix it in the next update
