### ISSUE TITLE
Auto update is broken in v1.1.0

### ISSUE THREAD

**Issue by aleksey-hoffman** [aleksey-hoffman/sigma-file-manager#104]
## Problem:
I accidentally broke the auto update feature in `v1.1.0`.
You will see an error, when you click the "download" button in the "update is available" notification.

Fixed in 35dfacc

## How to update?
When `v1.2.0` update is published, you will have to download it manually from the releases page:
https://github.com/aleksey-hoffman/sigma-file-manager/releases

I might have to implement some Spectron tests at some point, to avoid such issues in the future

**Comment by Ansh4011** [comment]
Hi @aleksey-hoffman, I am sorry for pinging you and messaging over here, I really couldn't resist from asking that when is the 1.2.0 version releasing! I am really dying for it😅. Thanks!

**Comment by aleksey-hoffman** [comment]
Good day @Ansh4011 I'm planning to publish the update today. Just need to fix a few small things

**Comment by Ansh4011** [comment]
> Good day @Ansh4011 I'm planning to publish the update today. Just need to fix a few small things

You don't know how Happy I am to know this 😀! A Big Big Big Big Very Big Thanks! 
Have a Great Day Ahead!

**Comment by aleksey-hoffman** [comment]
@Ansh4011 thanks, good to see people excited about the app :)

Btw, if you didn't know, you can track all the progress in real time on the `commits` page:

![image](https://user-images.githubusercontent.com/61761672/122799142-0ee44600-d2ca-11eb-91d6-38473c98bb3f.png)

**Comment by Ansh4011** [comment]
> @Ansh4011 thanks, good to see people excited about the app :)
> 
> Btw, if you didn't know, you can track all the progress in real time on the `commits` page:
> 
> ![image](https://user-images.githubusercontent.com/61761672/122799717-bb262c80-d2ca-11eb-9e44-8db19f94c4f9.png)
OH, That's new for me! Thanks for making me aware of it 😀! Actually I am new to Github with almost no knowledge about any programming language, haha!

(ps-> Don't mind my English, I am bad at it)

**Comment by aleksey-hoffman** [comment]
@Ansh4011 well, it's never too late to learn new things :)  

On that "commits" page, you can see all the changes I make in the app ("commit" basically means "change"). Every commit has a short description message. You can click on it to see what code and what files were changed in that commit.

When I send a commit with the description `"v1.2.0"`, you will see the `v1.2.0` update on the [releases page](https://github.com/aleksey-hoffman/sigma-file-manager/releases)

**Comment by Ansh4011** [comment]
> @Ansh4011 well, it's never too late to learn new things :)
> 
> On that "commits" page, you can see all the changes I make in the app ("commit" basically means "change"). Every commit has a short description message. You can click on it to see what code and what files were changed in that commit.
> 
> When I send a commit with the description `"v1.2.0"`, you will see the `v1.2.0` update on the [releases page](https://github.com/aleksey-hoffman/sigma-file-manager/releases)

Woah, that is super cool and sounds really interesting!
I tried it 😀!
Thanks a lot for the sincere help @aleksey-hoffman bro! 🙂

Also, wishing you a very Happy International Yoga Day!

**Comment by Ansh4011** [comment]
**You are a really Nice and Amiable person! Nice to meet you!**

btw, myself Ansh, I am a 10th grader from India!

**Comment by aleksey-hoffman** [comment]
@Ansh4011 nice to meet you too Ansh :)

I will finish the multi-language system in `v1.3` update. Will you help me translate the app into Hindi language?

**Comment by Ansh4011** [comment]
> @Ansh4011 nice to meet you too Ansh :)
> 
> I will finish the multi-language system in `v1.3` update and post instructions on how to translate the app. Will you help me translate the app into Hindi language?

Thanks for giving me the opportunity😀! 
I would love to do that! :)

**Comment by Ansh4011** [comment]
ps-> I will be able to translate it in between the next 1-2 months only bcz, after that we have our pre board and board exams (allover India exams) and it's preparation! And these exams determine how good my career will be, job opportunities, etc. in the future! 
Thanks 🙂

**Comment by aleksey-hoffman** [comment]
@Ansh4011 that's fine, there's no rush, the app can be translated in small parts

**Comment by Ansh4011** [comment]
> @Ansh4011 that's fine, there's no rush, the app can be translated in small parts

O-Okay! Thanks Bro :)

**Comment by aleksey-hoffman** [comment]
Fixed in 35dfacc

**Comment by aleksey-hoffman** [comment]
@Ansh4011 I will release the update in a few minutes
