### ISSUE TITLE
Making "open previous directory" more intuitive

### ISSUE THREAD

**Issue by Venitros** [aleksey-hoffman/sigma-file-manager#108]
Very nice update, feels much more pleasant to use. I noticed one weird quirk with the "open previous directory" hotkey/button.
Example when searching for something through folders.
You look in folder 1, then you can return to the root folder with the button/hotkey successfully. 
After returning, you look in folder 2, then returning will send you back to folder 1, even though you were in the root folder previously.

https://user-images.githubusercontent.com/85282550/123183497-55889a80-d49a-11eb-80df-c53fa15e8bca.mp4

**Comment by aleksey-hoffman** [comment]
Thanks, I will look into it

**Comment by aleksey-hoffman** [comment]
Fixed in 1e886e1 and added 2nd history navigation style.
Will appear in the next update in a few days
