### ISSUE TITLE
[Feature request] Add toggle to disable animations or Respect Windows "disable animations" toggle

### ISSUE THREAD

**Issue by sfchang92** [aleksey-hoffman/sigma-file-manager#11]
## Feature request:
I think that the multitude of animations might be detrimental for fast paced directory browsing. It would be helpful if the app follows the Windows system animations toggle, or having a disable/quicker animations toggle in the UI section in Settings. 

Could be biased since I usually turns off animations.

![image](https://user-images.githubusercontent.com/14126605/119507597-8c876580-bda1-11eb-8fcb-e713f0892cc4.png)

**Comment by sfchang92** [comment]
Also, personally feels that the "zoom" effect of the hover tooltips are less professional looking. A quick fade in might be nicer.

**Comment by aleksey-hoffman** [comment]
Thanks for the suggestion. I will try to implement it soon

**Comment by aleksey-hoffman** [comment]
Fixed in v1.2.0
