### ISSUE TITLE
Sigma wont open

### ISSUE THREAD

**Issue by AyanifyCC** [aleksey-hoffman/sigma-file-manager#112]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Alright so, I got sigma today, and first things first, its amazing, I love it, and I'd like to continue to use it, with of course a few issues.

I decided to close sigma with task manager, and after that happened, I tried reopening it, alas, no avail. I tried everything, restarting my PC, reinstalling it, and deleting it, and anything I do, it just wont reopen.

### Steps to reproduce

1. Open up task manager, and close sigma while its open
2. It should close, and then when you try and reopen it, it wont reopen.

### Environment

- OS: Windows 10
- App version: 1.2.0

**Comment by aleksey-hoffman** [comment]
Thank you for the feedback.
You probably enabled the "open in hidden state" option in the settings. 

If the app is ruining but not visible, you can show it by pressing `Ctrl+Shift+Space` or click "open window" from the tray icon menu

I need to figure out how to make it visible after the first launch if that option is enabled

**Comment by AyanifyCC** [comment]
Ah alright, I won't be able to use 1.2.0 as of right now, seeing the fact that 1.2.0 has a big issue on my side, I sent a new issue if you'd like to check it out.
