### ISSUE TITLE
Got a big issue after installing 1.2.0 again

### ISSUE THREAD

**Issue by AyanifyCC** [aleksey-hoffman/sigma-file-manager#113]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

After my first problem, I was using 1.1.0 instead of 1.2.0, and after my issue was resolved, I decided to reinstall 1.2.0, but when I did so, my antivirus program, (Avast) detected a threat, that being "IDP.Generic". Issue is that this never happened previously when i first installed 1.2.0. 

(This happened twice, when it first detected the virus, I moved it to quarantine, then reinstalled 1.2.0 then it got detected again)

### Steps to reproduce

I don't know the specifics but here we go;
1. Get Avast
2. Install 1.2.0, and just wait
3. Avast may or may not say "IDP.Generic" was found.

### Environment

- OS: Windows 10
- App version: 1.2.0

**Comment by aleksey-hoffman** [comment]
Related to #24
I'm not sure what can I do about this.

I will try to upload the app to Microsoft Store, rather than distributing it as an executable file. The app will then get a signed certificate, and maybe that will solve the issue.

**Comment by AyanifyCC** [comment]
Ah alright, very sorry if this is a big problem and such, I've read that its a false; positive the virus that is, but when I create and exception for the file, the installing for 1.2.0 gets interrupted. So if possible I'm going to install another antivirus to check if it really is a false positive. But I really appreciate the lengths you go to help out users it's really new!

**Comment by AyanifyCC** [comment]
Weird, ever since I created an exception, this started happening when I install 1.2.0
![image](https://user-images.githubusercontent.com/70831351/124001335-838e4300-d9a2-11eb-8a93-bf8d699736bb.png)

**Comment by aleksey-hoffman** [comment]
@AyanifyCC It seems your antivirus is locking the uninstaller file specified in the error message. Try adding it to exceptions and restart your computer.

**Comment by AyanifyCC** [comment]
Yep that worked, thank you! Ill try and get in touch with avast about this situation as well, so false positives like these dont occur again. Thank you for your time.
