### ISSUE TITLE
"Copy path to clipboard" shortcut not working

### ISSUE THREAD

**Issue by jczanfona** [aleksey-hoffman/sigma-file-manager#118]
This shortcut does not run: '_Copy path to clipboard_' `Ctrl + <` 
In any case I find more useful to add an option to right button called '_Copy file path_'

**Comment by aleksey-hoffman** [comment]
I will take a look.
You can also copy selected item's path in the info panel with `Ctrl + click`

**Comment by aleksey-hoffman** [comment]
The `Ctrl + <` shortcut works on my computer.
What OS and app version are you using?

**Comment by jczanfona** [comment]
Microsoft Windows [Versión 10.0.19042.1083]
Sigma v1.2.0

**Comment by aleksey-hoffman** [comment]
Please try the following:
- Focus and restart the app by pressing `Ctrl + Shift + R`
- Open console by pressing `Ctrl + Shift + i` (and then switch to "console" tab there)
- Navigate to any directory and press `Ctrl + <` shortcut
- See if the path was copied and if not, see if there's any errors in the console

**Comment by aleksey-hoffman** [comment]
Also, try the following:

1. In the console, paste the following code on a new line
```js
document.addEventListener('keydown', (event) => {
  console.log(event)
})
```
2. Focus the app window and press `Ctrl + <` shortcut
3. See the output in the console

You should see something like this:

![image](https://user-images.githubusercontent.com/61761672/124911256-34c15880-dff5-11eb-960f-81f4e1875d5c.png)

**Comment by jczanfona** [comment]
Nothing happens (no copy)
![image](https://user-images.githubusercontent.com/46503049/124913216-283a0180-dfef-11eb-9800-03daeccd7300.png)

**Comment by aleksey-hoffman** [comment]
Ok, I see the problem. Your keyboard returns code `IntlBackslash` instead of `Comma`. 
I will fix it in the next update.

If you want, you can check other shortcuts, and send me the screenshots of the same console output for the shortcuts that don't work, I will fix them as well.

**Comment by jczanfona** [comment]
`Ctrl + Plus` does not run, but `Ctrl + Minus` yes

![image](https://user-images.githubusercontent.com/46503049/124916004-78669300-dff2-11eb-998e-1a4862eeb4fb.png)

**Comment by jczanfona** [comment]
- `Esc` does not close the global search
- `Esc` does not close the confirm deleting window
- The shortcuts info window are not usable by keyboard (arrows, pag down, end, etc.)

**Comment by aleksey-hoffman** [comment]
@jczanfona does `Ctrl + >` work on your keyboard?

**Comment by jczanfona** [comment]
How to test?

**Comment by aleksey-hoffman** [comment]
It opens the path copied to the clipboard. You can just copy this path for example: `C:/` and then focus the app and press `Ctrl + >` if it opens the `C:/` directory, it's working. If not, please show me the console output

**Comment by jczanfona** [comment]
I maped this keys with other sw and shows me this:
![image](https://user-images.githubusercontent.com/46503049/124920209-5f141580-dff7-11eb-8037-0b2cb974a378.png)

Now I'm going to try what you said...

**Comment by jczanfona** [comment]
Nothing happens (not opening `c:\`)

![image](https://user-images.githubusercontent.com/46503049/124920740-f2e5e180-dff7-11eb-91fe-8728cbeb0b39.png)

**Comment by aleksey-hoffman** [comment]
Okay, for some reason your keyboard returns `IntlBackslash` code for both shortcuts `Ctrl + <` and `Ctrl + >`. 
I will try to fix it

Let me know if you find any other shortcuts not working on your keyboard
