### ISSUE TITLE
Setting: Save Changes to Default Sorting Options

### ISSUE THREAD

**Issue by JsephGriff** [aleksey-hoffman/sigma-file-manager#119]
## Feature request: 
A setting discoverable under UI Appearance, could allow the user to save their changes to default sorting options in order to stylize the app and save time. Example: to always by default display the most recently modified files first through the use of the existing system of sorting by date and changing the order to descending, however instead of having to change this dropdown setting every time the app launches, the users' choices would be saved.

**Comment by aleksey-hoffman** [comment]
I might add this in the next update

**Comment by aleksey-hoffman** [comment]
Fixed in dabaa2e
Will be released in v1.5 (today)
