### ISSUE TITLE
Administrator Privileges 

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#124]

**Comment by aleksey-hoffman** [comment]
Can you show me a screenshot?
I don't understand what you mean by "making changes to the data"

**Comment by Ansh4011** [comment]
> Can you show me a screenshot?
> I don't understand what you mean by "making changes to the data"

By making changes to the data, I meant like deleting the stuff. Bcz when I tried to delete a folder it rather asked for administrator privileges and then showed a failure in deleting it.

**Comment by Ansh4011** [comment]
Uhh.... I think last time there was some issue or I did some wrong step, this time it deleted the folder without any prompt or failure.

**Comment by aleksey-hoffman** [comment]
This was probably caused by Windows locking the folder. Or some other app was using it.

**Comment by Ansh4011** [comment]
Yea! Thanks for helping :)
