### ISSUE TITLE
Transfer files from the system into the app via clipboard

### ISSUE THREAD

**Issue by jczanfona** [aleksey-hoffman/sigma-file-manager#125]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Is not possible to copy a file shortcut (or folder) in a Windows folder 

### Steps to reproduce

1. Create a shortcut
2. Try to copy or move in a folder
3. The result is nothing.

If the shortcut is to a web page, it want to download the page, not copy the file with the link.

### Environment

- OS: Win 10
- App version: 1.2.0

**Comment by jczanfona** [comment]
Drag & Drop is ok, but Ctr+C & Ctrl+V does not copy (and the message appears indicating that it is going to do so)

**Comment by jczanfona** [comment]
I am doing Ctrl + C on the desktop (not from Sigma) and once I have activated the Sigma window I do Ctrl + V

**Comment by aleksey-hoffman** [comment]
Ok, I see, you are trying to copy a file from the system into the app. This functionality is not implemented yet.

**Comment by jczanfona** [comment]
And what about the web links? Is always trying to download...

**Comment by aleksey-hoffman** [comment]
@jczanfona I don't understand the issue with the links. Can you please explain it in more details? And perhaps show some screenshots as well? (on Windows you can quickly create screenshots by pressing `Shift + Win + S`)

Btw, it's better to create separate issues for different problems.

**Comment by jczanfona** [comment]
That is the file in the desktop
![image](https://user-images.githubusercontent.com/46503049/126997664-88a75b55-e4f8-4742-b064-107dcd9a9011.png)

**Comment by jczanfona** [comment]
And, after dropping, in the folder appear a html file, instead of the same file that in desktop is
![image](https://user-images.githubusercontent.com/46503049/126998170-5bebf99c-9d4e-4e98-bf34-896a6cb92a59.png)

**Comment by jczanfona** [comment]
An off-topic question, how to create a folder?

**Comment by aleksey-hoffman** [comment]
@jczanfona you can create a folder by pressing  `+` icon in the top toolbar or by pressing `Alt + N` shortcut.
