### ISSUE TITLE
Need help with #for-developers section

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#129]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

I was checking out [#for-developers](https://github.com/aleksey-hoffman/sigma-file-manager#for-developers), but I really don't get anything.... I installed [node.js](https://nodejs.org/en/) latest version in windows sandbox and other things like chocolatey, python, etc. also got installed via powershell, but then when I pasted the text '*cd ./sigma-file-manager && npm install && npm run electron:build*' it returned an error. What are we supposed to do in this?
![image](https://user-images.githubusercontent.com/84930340/129444352-e50cead8-8715-42f0-913b-da30bfe95e01.png)

### Steps to reproduce

1. 

### Environment

- OS: Windows 21H1
- App version: N/A

**Comment by jczanfona** [comment]
Have you tried to run the sentences one by one, without concatenate it with '&&'

**Comment by Ansh4011** [comment]
> Have you tried executing the sentences one by one, without concatenating them with '&&' ?

I tried that, but tbh I really don't know how to run this whole procedure. This is my first attempt.

**Comment by aleksey-hoffman** [comment]
Right now the app requires node `15.14.0`, you cannot run it on the latest version. 
You can download node `15.14.0` here: 
https://nodejs.org/dist/latest-v15.x/node-v15.14.0-x64.msi

If you don't have Git you can download it here: https://git-scm.com/downloads

First, you need to open powershell (or command prompt) in the directory that you want to download this project to, for example:

```
cd "C:/projects/"
```
cd command means "Change Directory"

Then download the project folder with the following command:

```
git clone https://github.com/aleksey-hoffman/sigma-file-manager.git
```

You can find this link here:
![image](https://user-images.githubusercontent.com/61761672/129451587-e7a3a35a-3f5e-40bc-a1de-418220c0414a.png)

Now you can enter these commands one by one if you are using Powerhsel or as 1 line if you're using command prompt:

Open the downloaded directory:
```
cd ./sigma-file-manager
```

Install app dependencies:
```
npm install
```

Run the app on local server:
```
npm run electron:serve
```

After this command, the app should automatically open. This is how you run the app on the local server. if you want to build the app installable, you need to run `npm run electron:build` instead

**Comment by Ansh4011** [comment]
> Right now the app requires node `15.14.0`, you cannot run it on the latest version.
> You can download node `15.14.0` here:
> https://nodejs.org/dist/latest-v15.x/node-v15.14.0-x64.msi
> 
> If you don't have Git you can download it here: https://git-scm.com/downloads
> 
> First, you need to open powershell (or command prompt) in the directory that you want to download this project to, for example:
> 
> ```
> cd "C:/projects/"
> ```
> 
> cd command means "Change Directory"
> 
> Then download the project folder with the following command:
> 
> ```
> git clone https://github.com/aleksey-hoffman/sigma-file-manager.git
> ```
> 
> You can find this link here:
> ![image](https://user-images.githubusercontent.com/61761672/129451587-e7a3a35a-3f5e-40bc-a1de-418220c0414a.png)
> 
> Now you can enter these commands one by one if you are using Powerhsel or as 1 line if you're using command prompt:
> 
> Open the downloaded directory:
> 
> ```
> cd ./sigma-file-manager
> ```
> 
> Install app dependencies:
> 
> ```
> npm install
> ```
> 
> Run the app on local server:
> 
> ```
> npm run electron:serve
> ```
> 
> After this command, the app should automatically open. This is how you run the app on the local server. if you want to build the app installable, you need to run `npm run electron:build` instead

Thanks a lot! 😃 I wanted to learn this from a long time.

**Comment by Ansh4011** [comment]
@aleksey-hoffman Thanks a lot for the kind support 😃. I wanted to learn how or if this is(which it is) possible from a long time.

**Comment by aleksey-hoffman** [comment]
@Ansh4011 no problem. Let me know if you have any questions

**Comment by Ansh4011** [comment]
> @Ansh4011 no problem. Let me know if you have any questions
Sure! Thanks Bhaiya! You are a really nice person.
