### ISSUE TITLE
Problem with disk drives, they're not found!

### ISSUE THREAD

**Issue by Shinobyc** [aleksey-hoffman/sigma-file-manager#13]
Error: Error: EISDIR, Ð£ÑÑÑÐ¾Ð¹ÑÑÐ²Ð¾ Ð½Ðµ Ð³Ð¾ÑÐ¾Ð²Ð¾.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)
![Снимок экрана (5)](https://user-images.githubusercontent.com/69596922/119513892-4ae4c380-bd7d-11eb-9f7c-d9d9496e7b6a.png)
_**Thank you for this file manager, it's look amazing, but i can not do anything with they until you fix the problem.**_

**Comment by LightShaft** [comment]
![image](https://user-images.githubusercontent.com/27209225/119519942-24715900-bd7a-11eb-902b-d9aed1bdf805.png)
Same problem here

**Comment by aleksey-hoffman** [comment]
@Shinobyc  @LightShaft  thank you guys. The problem is fixed.
I will release the update today.
