### ISSUE TITLE
Failed to get 'pictures' path

### ISSUE THREAD

**Issue by jackgreyhat** [aleksey-hoffman/sigma-file-manager#133]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Hello,

After the installation, upon first launch, the application crashes with "Failed to get 'pictures' path"

I must add that I am running this on a domain joined machine, with redirected Shell folders (info: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn789199(v=ws.11)
Shell folders are redirected to a network drive, which is accessible at the time of application execution.
Attached is a screenshot of the error:
![2021-08-23- 15_50_37 %pn](https://user-images.githubusercontent.com/37959739/130459164-15128b7d-075e-4b74-b68c-5154309a9b14.png)

Thanks.

### Steps to reproduce

1. Install application
2. Open application

### Environment

- OS: Windows 10 21H1
- App version: 1.3.0

**Comment by aleksey-hoffman** [comment]
Hello. I think I know what's causing the problem.
Can you please open powershell and run this command:
```
[Environment]::GetFolderPath('MyPictures')
```

And also this command in the command prompt:

```
cd %systemdrive%/Users/%username%/Pictures
```

Do you see the proper path to your Picture directory? Something like `C:/Users/Username/Pictures`

**Comment by jackgreyhat** [comment]
Hello.

`[Environment]::GetFolderPath('MyPictures')`
This returns nothing, and empty string I assume.

`cd %systemdrive%/Users/%username%/Pictures`
This points me to my local Pictures folder.

**Comment by aleksey-hoffman** [comment]
Thanks, could you also run this in powershell:
```
((New-Object -com Shell.Application).NameSpace(39)).Self.Path
```
Does it return `C:\Users\username\Pictures` ?

And if you have Node.js installed, also these 2 commands one by one:

```js
require('child_process').execSync('cd "%systemdrive%/Users/%username%/Pictures" && cd').toString()
```

```js
fs.readdirSync(process.env.USERPROFILE)
```

What do you see?

**Comment by jackgreyhat** [comment]
`((New-Object -com Shell.Application).NameSpace(39)).Self.Path`
This returns nothing, unfortunately.
I ran a quick loop, running across all array positions and was unable to find `C:\Users\username\Pictures`.
Only non-shell redirected folders show up here.

Node.js output:
`
C:\ $ node.exe
Welcome to Node.js v16.5.0.
Type ".help" for more information.
> require('child_process').execSync('cd "%systemdrive%/Users/%username%/Pictures" && cd').toString()
'C:\\Users\\username\\Pictures\r\n'
> fs.readdirSync(process.env.USERPROFILE)
[
  '3D Objects',
  'AppData',
  'Application Data',
  'Contacts',
  'Cookies',
  'Creative Cloud Files',
  'Desktop',
  'Documents',
  'Downloads',
  'Favorites',
  'IntelGraphicsProfiles',
  'Links',
  'Local Settings',
  'Music',
  'My Documents',
  'NetHood',
  'NTUSER.DAT',
  'ntuser.dat.LOG1',
  'ntuser.dat.LOG2',
  'NTUSER.DAT{8ba4e8d6-c851-11eb-ae68-005056c00008}.TM.blf',
  'NTUSER.DAT{8ba4e8d6-c851-11eb-ae68-005056c00008}.TMContainer00000000000000000001.regtrans-ms',
  'NTUSER.DAT{8ba4e8d6-c851-11eb-ae68-005056c00008}.TMContainer00000000000000000002.regtrans-ms',
  'ntuser.ini',
  'OneDrive',
  'Pictures',
  'PrintHood',
  'Recent',
  'Saved Games',
  'Searches',
  'SendTo',
  'Start Menu',
  'Templates',
  'Videos'
]
>
`

**Comment by aleksey-hoffman** [comment]
@jackgreyhat thank you for the report. I will implement a proper fix for this issue in v1.4 update (Saturday)

It seems that Node correctly resolves the path to your user directories.
If you run the following Node command, you should see the contents of your `/Pictures` directory (let me know if you don't):

```
fs.readdirSync(process.env.USERPROFILE + '/Pictures')
```

I just applied a temp fix and rebuilt the app for you. You can try to install it, if you'd like to see if it works:

### App build with a temporary fix:

https://drive.google.com/file/d/1tiYsRHfkAvMH8fskJsWoN-LKo7KPZ1Hq/view?usp=sharing

**Comment by aleksey-hoffman** [comment]
@jackgreyhat let me know if that fixed build is still not working for you, in that case, I will implement another fix.

Checking registry would be another way to get the paths:

```
reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "My Pictures"
```

But I think the current fix should do it.

**Comment by jackgreyhat** [comment]
Hello,

The temp build works, that's lovely.
Both method work.
`fs.readdirSync(process.env.USERPROFILE + '/Pictures')`
`reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "My Pictures"`
They both return the Pictures folder location.

Thanks for your quick assistance :]
👍
