### ISSUE TITLE
Show the file time in the info panel

### ISSUE THREAD

**Issue by jczanfona** [aleksey-hoffman/sigma-file-manager#136]
## Feature request:
In the information panel it would be useful to see the time of the file, in addition to the date, of the fields *created* and *modified* (2)

**Comment by aleksey-hoffman** [comment]
Makes sense. I might add it in the v1.4 update

**Comment by jczanfona** [comment]
TX a lot.

**Comment by aleksey-hoffman** [comment]
Added in 05d1786 . Will be released in v1.4 update.

Time stat will now be displayed next to the date stat:

![image](https://user-images.githubusercontent.com/61761672/131233732-cd79ceff-0be5-476b-9155-5d56e4cc85f9.png)

Also added new setting to control month display format 8401af7:

### Setting date / time month format "numeric" (default):

**USA**: 5/23/2021, 11:16 PM
**Japan**: 2021/5/23 23:16
**Russia**: 23.05.2021, 23:16
**Germany** 23.5.2021, 23:16

### Setting date / time month format "short":

**USA**: May 23, 2021, 11:16 PM
**Japan**: 2021年5月23日 23:16
**Russia**: 23 мая 2021 г., 23:16
**Germany** 23. Mai 2021, 23:16

![image](https://user-images.githubusercontent.com/61761672/131233883-f8acd0a2-9cf1-4fd7-981d-c4834d386cf9.png)

**Comment by aleksey-hoffman** [comment]
Added in 05d1786 . Will be released in v1.4 update.

Time stat will now be displayed next to the date stat:

![image](https://user-images.githubusercontent.com/61761672/131234021-1b8f3d77-a478-42fb-b431-72404e9487a1.png)

Also added new setting to control month display format 8401af7:

### Setting date / time month format "numeric" (default):

**USA**: 5/23/2021, 11:16 PM
**Japan**: 2021/5/23 23:16
**Russia**: 23.05.2021, 23:16
**Germany** 23.5.2021, 23:16

### Setting date / time month format "short":

**USA**: May 23, 2021, 11:16 PM
**Japan**: 2021年5月23日 23:16
**Russia**: 23 мая 2021 г., 23:16
**Germany** 23. Mai 2021, 23:16

![image](https://user-images.githubusercontent.com/61761672/131233883-f8acd0a2-9cf1-4fd7-981d-c4834d386cf9.png)
