### ISSUE TITLE
Overlay BG on ultrawide monitors not working properly

### ISSUE THREAD

**Issue by aalvesfelipe** [aleksey-hoffman/sigma-file-manager#137]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

I'm using the app on a ultrawide monitor and the images on overlay background get cropped on right portion of the screen.
Even when I'm using fit images. In the example below the image is a print of a game so it fit perfectly on my monitor (2560x1080px).

![image](https://user-images.githubusercontent.com/89800571/131380756-feddcc2d-0a36-445f-bc1c-af3fa9b24ea2.png)

![image](https://user-images.githubusercontent.com/89800571/131383184-19abdee6-871e-41f4-8d43-a27b1d1c0b75.png)

It is an issue or the app don't have ultrawide support yet?

### Steps to reproduce

1. 

### Environment

- OS: Windows 10
- App version: 1.3.0

**Comment by aleksey-hoffman** [comment]
Thanks for the report, I forgot to make the overlay size dynamic.
I will fix it for the v1.4 update (Saturday)

**Comment by aleksey-hoffman** [comment]
The update is out, please give it a try and let me know what you think
