### ISSUE TITLE
v1.4 dll initialization failed on launch

### ISSUE THREAD

**Issue by aleksey-hoffman** [aleksey-hoffman/sigma-file-manager#139]
Moved conversation to new issue:

> Hi, I have been trying to install the latest version of SFM and after every install when I launch it, it just gets stuck on the start screen. I have tried updating it via app and also by reinstalling it but none of them worked. I am not really sure what could be the cause though. 
> Edit- Facing the same issue in Windows Sandbox as well.
> 
> _Originally posted by @Ansh4011 in https://github.com/aleksey-hoffman/sigma-file-manager/discussions/138#discussioncomment-1281134_

**Comment by Ansh4011** [comment]
Hi, I installed both the builds, and both worked flawlessly. Also, I don't really know why but I felt a bit more smoothness in the second build. Thanks for the quick support!

**Comment by aleksey-hoffman** [comment]
@Ansh4011 thank you, can you also please try this 3rd versions. This will help me what exactly caused the issue:

### Modified version 3:
https://drive.google.com/file/d/15zXd0oHGPcb2DpVVWnUaHrB_dPMagPH5/view?usp=sharing

**Comment by aleksey-hoffman** [comment]
@Ansh4011 thank you, can you also please try this 3rd versions. This will help me understand what exactly caused the issue:

### Modified version 3:
https://drive.google.com/file/d/15zXd0oHGPcb2DpVVWnUaHrB_dPMagPH5/view?usp=sharing

**Comment by Ansh4011** [comment]
> @Ansh4011 thank you, can you also please try this 3rd versions. This will help me understand what exactly caused the issue:
> 
> ### Modified version 3:
> https://drive.google.com/file/d/15zXd0oHGPcb2DpVVWnUaHrB_dPMagPH5/view?usp=sharing

Sure!

**Comment by Ansh4011** [comment]
> @Ansh4011 thank you, can you also please try this 3rd versions. This will help me understand what exactly caused the issue:
> 
> ### Modified version 3:
> https://drive.google.com/file/d/15zXd0oHGPcb2DpVVWnUaHrB_dPMagPH5/view?usp=sharing

The third build just got installed, and this got stuck at the same point as well. Here is what the dev. tools show-
![image](https://user-images.githubusercontent.com/84930340/132106796-eb968a59-01a6-49e3-8fb1-4dedbd0b9498.png)

**Comment by aleksey-hoffman** [comment]
@Ansh4011 thank you brother. You really helped me find the problem quickly! I will update the release file asap

**Comment by Ansh4011** [comment]
> @Ansh4011 thank you brother. You really helped me find the problem quickly! I will update the release file asap

@aleksey-hoffman Thanks to you too for the kind and quick support :) Good Night!

**Comment by aleksey-hoffman** [comment]
By the way, when replying on Github you don't need to "quote reply" to the message.
The person who created the issue will get notified automatically. And if you want to send someone notification, all you need to do is to write their name like that @Ansh4011 in the comment and they will get a notification.

These "quoted" replies clutter the comments

**Comment by Ansh4011** [comment]
Oh, thanks! I'll keep that in mind. :)

**Comment by aleksey-hoffman** [comment]
@Ansh4011 quoting a specific

**Comment by aleksey-hoffman** [comment]
@Ansh4011 quoting a specific line is fine, but when the whole comment is quoted, it gets difficult to read the comments, especially when the comment takes half of the screen :)

**Comment by jczanfona** [comment]
Upppps from the application update process it is not possible to catch the update ...

**Comment by aleksey-hoffman** [comment]
@jczanfona hello, can you please create a new issue? I just tried updating from within the app and it worked

**Comment by jczanfona** [comment]
https://github.com/aleksey-hoffman/sigma-file-manager/issues/140

**Comment by Ansh4011** [comment]
@aleksey-hoffman Indeed! Even I felt so. Thanks :)

**Comment by aleksey-hoffman** [comment]
@Ansh4011 hi, could you please install another version of the app and let me know if it's working?
### Modified version 4
https://drive.google.com/file/d/1zV6Q_HVkHMgwbVJqSMRjPMUFGn92U9Y0/view?usp=sharing

**Comment by aleksey-hoffman** [comment]
@Ansh4011 hi, could you please install another version of the app and let me know if it's working on your computer?
### Modified version 4
https://drive.google.com/file/d/1zV6Q_HVkHMgwbVJqSMRjPMUFGn92U9Y0/view?usp=sharing

**Comment by aleksey-hoffman** [comment]
@Ansh4011 could you please install another version of the app and let me know if it's working?
### Modified version 4
https://drive.google.com/file/d/1zV6Q_HVkHMgwbVJqSMRjPMUFGn92U9Y0/view?usp=sharing

**Comment by Ansh4011** [comment]
Sure!

**Comment by Ansh4011** [comment]
Hi, the 4th build works fairly well indeed! But I honestly felt a little more smoothness in the 2nd build like when I am switching among directories very quickly so the lag was the least in my pc, but also know it that my pc is not of high end so maybe it could be due to my pc too! Thanks!
Btw, Happy Teacher's Day @aleksey-hoffman.

**Comment by aleksey-hoffman** [comment]
@Ansh4011 thank you for testing it! 
There shouldn't be any difference in performance between the 1st and 2nd versions. In the 4th version I updated `fswin` module, which actually might have some impact on the performance. 

Perhaps the the 2nd build felt smoother because you computer wasn't doing any other tasks in the background at that time.

Is there a big performance difference between the 2nd and 4th builds when browsing directories?

> Happy Teacher's Day

Thanks :) I actually wanted to create a website where I would teach people how to design and develop (code) apps and websites.
The first 100 people who support me on Patreon will get a free lifetime access to this website.

**Comment by aleksey-hoffman** [comment]
@Ansh4011 thank you for testing it!
There shouldn't be any difference in performance between the 1st and 2nd versions. In the 4th version I updated `fswin` module, which actually might have some impact on the performance.

Perhaps the 2nd build felt smoother because you computer wasn't doing any other tasks in the background at that time.

Is there a big performance difference between the 2nd and 4th builds when browsing directories?

Happy Teacher's Day

Thanks :) I actually wanted to create a website where I would teach people how to design and develop (code) apps and websites.

**Comment by Ansh4011** [comment]
> Is there a big performance difference between the 2nd and 4th builds when browsing directories?

Well, the difference was really very less. Like one can only notice it if they tried both the versions atleast a few times. So I would say near to negligible.
> Thanks :) I actually wanted to create a website where I would teach people how to design and develop (code) apps and websites.

WOW! That's super cool. In that case, you got your first student :)

**Comment by aleksey-hoffman** [comment]
> difference ... near to negligible

Ok, thanks. I will do some testing to make sure the difference was not caused by the fix.

> you got your first student :)

I'm not sure when I will finish this website. I think it might take a few months. I will announce it on my [Twitter](https://twitter.com/hoffman_aleksey) when I publish it. I already created a few text tutorials with code examples for that website. 

But I think teaching people personally on the Discord chat of this app will be more effective. This way people can ask any question they want and I could give them a detailed explanation. Some of my [Patreon](https://www.patreon.com/sigma_file_manager) supporters get access to that chat as one of the rewards

**Comment by Ansh4011** [comment]
> Ok, thanks. I will do some testing to make sure the difference was not caused by the fix.
 Sure, Do let me know if I could help you out with anything! :)

> I'm not sure when I will finish this website. 
> But I think teaching people personally on the Discord chat of this app will be more effective.

Indeed! Many people find it hard to communicate in public.
