### ISSUE TITLE
The update process does nothing

### ISSUE THREAD

**Issue by jczanfona** [aleksey-hoffman/sigma-file-manager#140]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

The *second version* of 1.4.0 is not available through the application update process 

### Steps to reproduce

1. Run update

### Environment

- OS: W10
- App version: 1.4.0

**Comment by aleksey-hoffman** [comment]
Which version do you have installed? Is it v1.3 or v1.4? What does it say on the settings page here?

![image](https://user-images.githubusercontent.com/61761672/132108355-f14e42d0-cbda-4456-ab2d-60fd0054fb01.png)

**Comment by aleksey-hoffman** [comment]
Which version do you have installed? What does it say on the settings page, is it v1.3 or v1.4?

![image](https://user-images.githubusercontent.com/61761672/132108355-f14e42d0-cbda-4456-ab2d-60fd0054fb01.png)

**Comment by aleksey-hoffman** [comment]
What happens when you click "check for updated now" button?

**Comment by jczanfona** [comment]
I have the first one 1.4.0, previous at the new update with the fswin downgrade.
The button says the is no update available.

**Comment by aleksey-hoffman** [comment]
@jczanfona okay. I see the problem.
The app will only get the update if the version is higher than the installed one. For example, `1.4.0` => `1.4.1`.

I didn't release a new version. I just updated the installer file on Github. The second (fixed) version of `v1.4.0` also has ``1.4.0`` tag.

**Comment by jczanfona** [comment]
yessss

**Comment by aleksey-hoffman** [comment]
So did you also encounter the problem with the first version of `v1.4.0` installer file?

**Comment by jczanfona** [comment]
no, everything is ok

**Comment by aleksey-hoffman** [comment]
Okay, that's good. And the seconds version of `v1.4.0` also works without problems?

**Comment by jczanfona** [comment]
I don't know... I'm ussing the first one
As long as it does not give problems I will continue using it

**Comment by aleksey-hoffman** [comment]
Ok. Well, when I release a new update with a bigger tag for example `v1.5.0` the app should get the update automatically. It checks for updates every 6 hours.

**Comment by aleksey-hoffman** [comment]
Thank you for the report anyway
