### ISSUE TITLE
Sorting the data

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#141]
### Is there an existing issue for this?

- [x] I have searched the opened issues

### Problem description

Hi, I was sorting my data according to date created descending order and as soon as I restarted the app, it again went back to the default sorting scheme. Is there any way that the sorting scheme stays in the memory permanently till we don't modify it? Thanks!

### Steps to reproduce

1. Start Sigma File Manager.
2. Open any Directory.
3. Now modify the sorting options.
4. Close the app completely (from system tray as well).
5. Now start it again and check for the sorting options in any directory. 

### Environment

- OS: Windows 21H1
- App version: 1.4.0 (build 2)

**Comment by aleksey-hoffman** [comment]
Duplicate of #119 

Yeah, I forgot about this. I will fix this in v1.5 update.

**Comment by Ansh4011** [comment]
Oh, sorry I didn't knew that it's a duplicate. Thanks!

**Comment by aleksey-hoffman** [comment]
Fixed in dabaa2e
Will be released in v1.5 (today)
