### ISSUE TITLE
PDF Quickview

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#144]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Hi, I really personally like this new quickview feature, but I realised that apparently it is not working with pdf files, it just shows an empty grey screen. Have a look -
![image](https://user-images.githubusercontent.com/84930340/132181561-60f9c13c-6484-4614-80a8-902fcad4b343.png)

### Steps to reproduce

1. Initiate SFM.
2. Select any pdf file.
3. Now press the space button for a quick view.

### Environment

- OS: Windows 10 21H1
- App version: 1.4.0

**Comment by Ansh4011** [comment]
Btw, is it possible to get options such as at which quality we want to download videos (suppose from youtube, only for testing purposes). This would be really helpful. Thanks!

**Comment by aleksey-hoffman** [comment]
Thank you, I'm aware of the problem with PDF preview. The issue is caused by Electron, they changed something and broke it.

**Comment by aleksey-hoffman** [comment]
> options such as at which quality we want to download videos

Please open a separate issue for this

**Comment by Ansh4011** [comment]
> I'm aware of the problem..... and broke it.

Oh, okay! No worries. 
> Please open a separate issue for this

Sure

**Comment by aleksey-hoffman** [comment]
Fixed in 6740b39

**Comment by Ansh4011** [comment]
Awesome.... Hope you are doing great bro. Much excited for this release! All the best 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ansh4011** [comment]
Hey Aleksey, how have you been mate?
Congrats on 1k stars 😄🤟

**Comment by aleksey-hoffman** [comment]
@Ansh4011 hey Ansh! Thank you :) 
I'm doing fine. How are you?

**Comment by Ansh4011** [comment]
@aleksey-hoffman Doing well too, thanks :).
