### ISSUE TITLE
Reassigned mouse back button functionality

### ISSUE THREAD

**Issue by Khachdallak02** [aleksey-hoffman/sigma-file-manager#147]
I don't think this is a common issue, but I always use Mouse back button to navigate. Mouse back button goes back to the home directory, instead of going back to previous folder you have been. Maybe this requires complete rework in which case the feature is not worse it.

**Comment by SweetyVolty** [comment]
Uhhm can I add another mouse related thing; I use ctrl+W to terminate windows and sigma does not respond to this go away shortcut :'(

**Comment by aleksey-hoffman** [comment]
Mate it already has a setting for re-assigning the mouse button functions:

![image](https://user-images.githubusercontent.com/61761672/132237926-47d94f88-8b5d-4755-a7d7-fa0dd370b612.png)

**Comment by Khachdallak02** [comment]
Thank you. I didn't see the settings.

**Comment by aleksey-hoffman** [comment]
> sigma does not respond to this go away shortcut :'(

@SweetyVolty don't be sad now, I just added:

- 9e08e4e:  `Ctrl + W` shortcut to close current tab / window (when the last tab is closed)
- 04a2430:  `Ctrl + Shift + W` shortcut to close all tabs in current workspace
- bfbafb4:  `Ctrl + Q` shortcut to close the app window without closing tabs
- c2e1328: 1 new settings to control the tab closing behavior

Just for you

![image](https://user-images.githubusercontent.com/61761672/132957154-37cc0848-bd33-423e-b1a7-1b3c271ad8dd.png)

![image](https://user-images.githubusercontent.com/61761672/132955917-8951c8ab-8259-4fca-99e6-0d03398af9fb.png)
