### ISSUE TITLE
Add Window Control: Minimize to taskbar

### ISSUE THREAD

**Issue by douglasparker** [aleksey-hoffman/sigma-file-manager#148]
## Feature request:
Please add the following options to the Window Controls in Settings:

- Minimize to taskbar and keep in memory
- Minimize to taskbar and minimize memory usage

The reason for this is because out of habit I always hit the X button to close apps, and then it'll go to the system tray. Normally this would be fine, but whenever I try and open it up from the pinned icon in my taskbar, it doesn't actually work.

I am required to right click the icon in the system tray to open it again, or to use the shortcut.

I wouldn't mind closing it out completely and then using the taskbar icon to reopen it, but the startup is just too slow for that.

**Comment by aleksey-hoffman** [comment]
Thanks for the suggestion. I might add it in the next update.
I will fix the taskbar icon issue in the next update, so you can actually click it


You can also toggle the window visibility with global shortcut: `Ctrl + Shift + Space`
It will show / minimize the window to taskbar.
