### ISSUE TITLE
Pinned folders in 1 click

### ISSUE THREAD

**Issue by michael-dm** [aleksey-hoffman/sigma-file-manager#152]
I like the fact that my Desktop, Documents or Pinned folders are 1 click away in Windows explorer (and Finder). I find it more complicated to reach them fast (even with shortcuts) with Sigma.

**Comment by aleksey-hoffman** [comment]
Hi, thanks for the feedback.
There's a setting for this:

![image](https://user-images.githubusercontent.com/61761672/169566741-438a662f-fb37-4534-be01-395e0dd653fe.png)

By the way, I'm planning to release a big update in June, Stay tuned :)
