### ISSUE TITLE
Drivers not show after i updated app to newest version

### ISSUE THREAD

**Issue by Makezu90** [aleksey-hoffman/sigma-file-manager#160]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

I updated app to 1.4.0 from 1.3.0 but now i can't see any drivers. Is there any fix? I tried already rescan but nothing..

Anybody has same problem?

### Steps to reproduce

1. 

### Environment

- OS: Windows 11
- App version: 1.4.0

**Comment by aleksey-hoffman** [comment]
Fixed in 0fdbd32
Release: v1.5
