### ISSUE TITLE
Delete button overrided by single click open

### ISSUE THREAD

**Issue by EDTA-gif** [aleksey-hoffman/sigma-file-manager#165]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

When "Settings->Input->Navigator->Open with single click" is on, clicking on the delete button will no longer remove the item. The click will open the folder in higher priority.
This gif shows the case of the "Pinned" tab on the Dashboard, the "Protected" and "Timeline" tabs are also affected.
![动画](https://user-images.githubusercontent.com/57220620/137402407-48569e35-dd35-4a79-ad29-76ae04204cb8.gif)

### Steps to reproduce

1.Open "Settings->Input->Navigator->Open with single click"
2.Instead of removing it, clicking the cross on any folder on pinned/protected/timeline tab in dashboard will open it.

### Environment

- OS: Windows 10
- App version: 1.4.0

**Comment by aleksey-hoffman** [comment]
Thank you for the detailed report. I will fix this issue in the next update.

**Comment by aleksey-hoffman** [comment]
Fixed in 3d904b7
Will be released in v1.5 (today)
