### ISSUE TITLE
[Problem report] The background manager needs another file explorer or instance to use

### ISSUE THREAD

**Issue by thebluedev** [aleksey-hoffman/sigma-file-manager#17]
## System info:
- **App version**:  1.0.0 
- **Operating System**:  x64 | Windows 10 

## Problem:

As the title states, when trying to change the background on the home page to something custom, It is not possible to paste nor drag and drop a link. 
![image](https://user-images.githubusercontent.com/73629408/119524566-619a1300-bd9b-11eb-8665-eee990ecfbe6.png)

Drag and drop a photo? how? open another file manager? that defeats the purpose of sigma! 
Open another instance? This would be viable if the start up time was less but is just bother some.

## Fix? 
![image](https://user-images.githubusercontent.com/73629408/119524677-7c6c8780-bd9b-11eb-8218-415d7e2f8473.png)

Make it so that clicking the highlighted region will open up a "explorer window" like this one
![image](https://user-images.githubusercontent.com/73629408/119524920-b2117080-bd9b-11eb-9b78-b502c0a0c2ff.png)

**Comment by aleksey-hoffman** [comment]
The drag and drop feature is needed when you're dragging files from the internet browser, for example.
Sure, I will add the ability to click & select as well.

**Comment by thebluedev** [comment]
Great!

**Comment by aleksey-hoffman** [comment]
Fixed in [9e9a824](https://github.com/aleksey-hoffman/sigma-file-manager/commit/9e9a82409a3c41932f260e65bab84a9999e7ba68)
Will appear in the next (v1.8) update

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/61761672/bb47613c-6bf5-4b55-b0af-930bd8b2d866)
