### ISSUE TITLE
Type/Paste path

### ISSUE THREAD

**Issue by KPMTGG** [aleksey-hoffman/sigma-file-manager#172]
## Feature request:
Maybe it does this, but I looked everywhere and did not find it, but I would like to type or paste in a path and have it open to that path.
Overall, very cool work.  It is really nice!

**Comment by aleksey-hoffman** [comment]
Yes, you can type in the path manually

This is version v1.5 (not released yet) but it should look similar in v1.4:

![image](https://user-images.githubusercontent.com/61761672/154571942-5e8f9c67-0f52-4e5a-af4a-84ad23a42009.png)

**Comment by aleksey-hoffman** [comment]
Btw, I will release the v1.5 version with a lot of fixes and new features in several days. It needs about 10 more days of work before I can publish it

**Comment by Ansh4011** [comment]
And we got a sneak peek of v1.5 too.... Yayy.... Excited!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KPMTGG** [comment]
Nice!  Thank you for your response!!

**Comment by KPMTGG** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Roboto;
	panose-1:2 0 0 0 0 0 0 0 0 0;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
