### ISSUE TITLE
Add second additionally as time format

### ISSUE THREAD

**Issue by xfrisakbaeun** [aleksey-hoffman/sigma-file-manager#179]
## Feature request:
It would be great to have the choice if the seconds are shown under Info Panel.

**Comment by aleksey-hoffman** [comment]
Hi, thanks for the suggestion. Do you mean seconds for the date?

![image](https://user-images.githubusercontent.com/61761672/170324299-74cc40e9-d86c-4e9a-a76e-dba57d4532c9.png)

**Comment by xfrisakbaeun** [comment]
> Hi, thanks for the suggestion. Do you mean seconds for the date?
> 
> ![image](https://user-images.githubusercontent.com/61761672/170324299-74cc40e9-d86c-4e9a-a76e-dba57d4532c9.png)

Exactly e.g 27 Jan 2022, 04:23:07

Another suggestion, I read there are still nanoseconds and NTFS has 100 nanoseconds precision. I like that too, but should only be offered as an option and disabled by default.

27 Jan 2022, 04:23:07.1234567

**Comment by xfrisakbaeun** [comment]
Thanks for quick reply.

**Comment by aleksey-hoffman** [comment]
It took me only 10 minutes to implement this feature, so I decided to add this in v1.5
Closed in [b792520](https://github.com/aleksey-hoffman/sigma-file-manager/commit/b792520aa9769cc48f09c72bf22a051ee179adda)

![image](https://user-images.githubusercontent.com/61761672/170384551-ef116395-bf05-409d-afb4-a70423fc9605.png)

![image](https://user-images.githubusercontent.com/61761672/170384840-29f018a4-8094-4502-9988-4fb8aecb6d01.png)

**Comment by xfrisakbaeun** [comment]
> It took me only 10 minutes to implement this feature, so I decided to add this in v1.5 Closed in [b792520](https://github.com/aleksey-hoffman/sigma-file-manager/commit/b792520aa9769cc48f09c72bf22a051ee179adda)
> 
> ![image](https://user-images.githubusercontent.com/61761672/170384551-ef116395-bf05-409d-afb4-a70423fc9605.png)
> 
> ![image](https://user-images.githubusercontent.com/61761672/170384840-29f018a4-8094-4502-9988-4fb8aecb6d01.png)

Thank you, you are great and very fast. If you want you can offer nanoseconds as an extra option in the future. It's just fun to activate these options.
