### ISSUE TITLE
Can't build project on Ubuntu 22.04

### ISSUE THREAD

**Issue by PhilLovesToCode** [aleksey-hoffman/sigma-file-manager#183]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Hello,
I tried to clone and build this project on my Ubuntu 22.04 development machine with no success.  In summary, I encountered errors at every stage. The first set of errors had to do with dependency resolution.  I was only able to fix those by npm removing all of the dependencies that reported errors and re-installing them one by one.  However this left me with versions that differed from the original package.json, which likely caused subsequent errors.  When trying to run the electron app, I again encountered numerous code errors. I fixed one or two but they kept coming, so I gave up.

Has anyone successfully built this project on Ubuntu or any other Linux distro?  If so, could the contributors please find a way to update the app so it will successfully build and run on all three platforms: Windows, Mac OS, and Linux?

Thanks in advance for any help anyone can provide.
-Phil

### Steps to reproduce

1. Clone and build the project on Ubuntu 22.04.

### Environment

- OS: Ubuntu 22.04
- App version:  Latest clone

**Comment by aleksey-hoffman** [comment]
Hi @PhilLovesToCode I just tried to build the latest commit on Ubuntu 21.10 with `npm run electron:serve` and it launched in dev with no errors

Can you please show me the errors you are getting?

**Comment by PhilLovesToCode** [comment]
Thanks for your quick response. I'll try the Node and NPM versions you provided and report back.

**Comment by PhilLovesToCode** [comment]
Success!  I was able to build and run the project with Node 15.14.0 and NPM 7.7.6.  When I npv installed Node 15.14.0, it automatically installed NPM 7.7.6, so I stuck with that version.  The code I cloned was the latest as of a few hours ago.  Thanks for your help, and congratulations on building an outstanding app!

**Comment by aleksey-hoffman** [comment]
@PhilLovesToCode thanks for the feedback, mate! It will only get better with every update
