### ISSUE TITLE
Winget package name is different

### ISSUE THREAD

**Issue by fl4pj4ck** [aleksey-hoffman/sigma-file-manager#187]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Readme specifies the following winget command to install Sigma:
`winget install sigma`

The result is as follows:
```
Multiple packages found matching input criteria. Please refine the input.
Name               Id                                Source
------------------------------------------------------------
Sigma File Manager 9N7W62ND0NF9                      msstore
Sigma file manager AlekseyHoffman.Sigma-File-Manager winget
```

### Steps to reproduce

1. In Terminal, type `winget install sigma`

### Environment

- OS: Windows 11
- App version: --

**Comment by aleksey-hoffman** [comment]
Hi, thanks for the feedback, I will edit the command to make it clearer.

You can install it from either of these sources by specifying the `--source` attribute:

#### Winget
```
winget install sigma --source winget
``` 

#### MS store
```
winget install sigma --source msstore
```
