### ISSUE TITLE
[Problem report] Opening the global search does not allow to continue browsing current directory

### ISSUE THREAD

**Issue by thebluedev** [aleksey-hoffman/sigma-file-manager#19]
## System info:
- **App version**: 1.0.0
- **Operating System**: x64 | Windows 10

### I'm not sure if this was intended or a bug

Cannot scroll down, see arrows
![image](https://user-images.githubusercontent.com/73629408/119528264-ac695a00-bd9e-11eb-82ac-35e393d139ee.png)

Steps to reproduce
1. Open any folder with some files and folders
2. Open the global search
3. Cannot scroll down to see files only folders visible

**Comment by aleksey-hoffman** [comment]
Fixed in 8f0ecfd
Will be released in v1.5 (today)

I moved the search widget to the side

![image](https://user-images.githubusercontent.com/61761672/183314792-f58fd3ce-d806-490e-99fb-d9d1b32734ff.png)
