### ISSUE TITLE
[Auto-generated problem report] unhandled error

### ISSUE THREAD

**Issue by Eccomi21** [aleksey-hoffman/sigma-file-manager#195]
## System info:
- **App version**: 1.5.0
- **App page**: navigator
- **Operating System**: x64, win32, 10.0.19044
- **Free memory**: 19.3 GB
### Error:
```js
Uncaught Error: unexpected end of file

```
### App action history:
```js
00:42:40:541 | App.vue::created()
00:42:40:614 | App.vue::mounted()
00:42:40:777 | store.js::UPDATE_STORAGE_FILE()
00:42:40:831 | App.vue::initAllStorageFiles()
00:42:41:209 | store.js::UPDATE_STORAGE_FILE()
00:42:42:806 | store.js::LOAD_DIR()
00:42:47:989 | store.js::UPDATE_STORAGE_FILE()
00:43:10:694 | store.js::UPDATE_STORAGE_FILE()
00:43:10:946 | store.js::UPDATE_STORAGE_FILE()
00:43:26:740 | store.js::UPDATE_STORAGE_FILE()
00:43:26:748 | App.vue::initAllStorageFiles()
00:43:27:004 | store.js::UPDATE_STORAGE_FILE()

```

**Additional Info:** Was attempting a global search with the word "crossover"

I believe the app errored out because i attempted the search by pressing enter before the drive scan was completed

**Comment by aleksey-hoffman** [comment]
Hi, thanks for the feedback. I fixed this issue in 9824d72
Will be released in the next update
