### ISSUE TITLE
Enter key doesn't work in confirmation prompts

### ISSUE THREAD

**Issue by Alaknar** [aleksey-hoffman/sigma-file-manager#205]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Doesn't work on confirmation prompts. E.g. [Shift]+[Del] an item, get a confirmation prompt, press [Enter] - nothing happens. So you technically need three hands to operate this app comfortably. ;)

### Steps to reproduce

1. Select an item.
2. [Shift]+[Del] on keyboard.
3. A confirmation prompt appears.
4. Press [Enter].

**Expected Result**
[Enter] is the confirmation on the prompt and the operation continues.

**Actual result**
Absolutely nothing happens. :( 

### Environment

- OS: Windows 22H2 (19045.2604)
- App version: 1.6.0

**Comment by aleksey-hoffman** [comment]
Added `Enter` shortcut to conformation prompts
