### ISSUE TITLE
Switching out of Navigator and back resets folder position

### ISSUE THREAD

**Issue by Alaknar** [aleksey-hoffman/sigma-file-manager#208]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Switching from Navigator to any other screen (e.g. Dashboard or Settings) and back to Navigator resets the folder position all the way back to `%userprofile%`.

### Steps to reproduce

1. Navigate to a folder, say, `C:\Temp`.
2. Switch to Notes.
3. Switch back to Navigator.

**Expected result**
Navigator opens and displays `C:\Temp`.

**Actual result**
Navigator opens and displays `%userprofile%`.

### Environment

- OS: 22H2 (19045.2604)
- App version: 1.6.0

**Comment by aleksey-hoffman** [comment]
Solved in 5f795e5
Will appear in the next update

**Comment by aleksey-hoffman** [comment]
Solved in https://github.com/aleksey-hoffman/sigma-file-manager/commit/5f795e56703f4101b2433e0c819de21e961a5939
Will appear in the next update

https://user-images.githubusercontent.com/61761672/219977555-556ba671-1197-4a94-8640-5e01fed7b226.mp4
