### ISSUE TITLE
 [Problem report] Keyboard shortcuts not working.

### ISSUE THREAD

**Issue by thebluedev** [aleksey-hoffman/sigma-file-manager#21]
## System info:
- **App version**: 1.0.0
- **Operating System**: x64 | Windows 10

## Problem:

![image](https://user-images.githubusercontent.com/73629408/119541496-19372100-bdac-11eb-9a0c-7c744b37fea6.png)
From the above mention shortcuts only `alt + w` and `alt + s` work.

The arrow keys do nothing and the backspace key does not move up a directory (Yes I now we can press `alt + Q` but after so many years of using backspace it feels like it would be nice to have that as an option too.

**Comment by thebluedev** [comment]
Also would be great if we could change the file size through `ctrl + scroll`

Like this
[sample from File explorer](https://i.imgur.com/Q05uxd9.mp4)

**Comment by aleksey-hoffman** [comment]
@thebluedev sure, I will add the ability to set custom item size in the future

**Comment by thebluedev** [comment]
## Correction: most of the Keyboard short cuts do not work

**Comment by aleksey-hoffman** [comment]
All shortcuts except `ALT + A` and `ALT + D` work on my system.
Is your system main language set to English? 

Does anyone else have this problem?
What shortcuts do not work?

**Comment by thebluedev** [comment]
The copy path to clipboard shortcut does it work?

**Comment by aleksey-hoffman** [comment]
"Copy path to clipboard" also doesn't work. Will fix all the shortcuts now

**Comment by aleksey-hoffman** [comment]
"Copy path to clipboard" also doesn't work
Will be fixed in the next update today
