### ISSUE TITLE
Let users choose their terminal app

### ISSUE THREAD

**Issue by phreakadelle2k** [aleksey-hoffman/sigma-file-manager#216]
It's awesome that you can simply open a terminal at any location (also with elevated rights) via context menu.

But, currently the default seems to be cmd.exe. I personally prefer to use [Windows Terminal](https://www.microsoft.com/store/productId/9N0DX20HK701).

Please don't force users to go with the frumpy CMD. :)

Consider making it an option in the settings.

**Comment by aleksey-hoffman** [comment]
Yep, I wanted to add ability to change default terminal for awhile. Will add it in the next update 

Btw, thanks for approving PRs

**Comment by phreakadelle2k** [comment]
That sounds great. Besides that: Awesome file manager! :) Was looking for an alternative to the explorer for a while. Finally found one with Sigma!

About that PR: You're welcome! But I really hope that you actively merged it and it was not some kind of auto-merge, because of my approval. :D

**Comment by aleksey-hoffman** [comment]
> I really hope that you actively merged it
That's right, just saw an approval, glanced over the changes and merged it manually

**Comment by aleksey-hoffman** [comment]
Added in v1.7 (unreleased yet)

https://twitter.com/sigma__dev/status/1666856068469731349?s=20

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/61761672/6a363aba-303a-4a63-b6d5-3b719a359ec4)
