### ISSUE TITLE
Hidden files still shown and drivers too many.

### ISSUE THREAD

**Issue by lixiaoqi-LXQ** [aleksey-hoffman/sigma-file-manager#224]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Hi I'm having fun with the app on my arch linux, but I get 2 disappointing problem:

1.**Hidden files**: The files with name starting with "." are still shown even though I closed the option "Show Hidden Items"
2. **Drivers Icon**: 8 drivers are shown in the left bottom area, but actually the first one is /boot I don't  care about, and the other 7 ones lead to same root partition(this is because I have windows on my computer and windows partitions are not mounted automatically when booting linux). So I'm trying to find a way to customize these icons.
![2023-03-05_16-22](https://user-images.githubusercontent.com/73952617/222950198-15994529-a0cc-4d9c-abec-5fb92968f138.png)

### Environment

- OS: archlinux 6.2.1-arch1-1
- App version: 1.6.0

**Comment by aleksey-hoffman** [comment]
Thanks for the report. I will see if I can fix it for the next update
