### ISSUE TITLE
Not generating thumbnails

### ISSUE THREAD

**Issue by vfxninjaeditor** [aleksey-hoffman/sigma-file-manager#227]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

I just downloaded the app and started testing it out. It will not generate thumbnails for image or video. I looked in the settings, checked other issues, and can't find any solutions

### Steps to reproduce

1. 
No steps to note, just isn't generating thumbnails out of the box.

### Environment

- OS: Windows 10
- App version: 1.6.0

**Comment by aleksey-hoffman** [comment]
Hey, thanks for the report. It seems like the problem only occurs in the MS store version. I'll look into it

**Comment by aleksey-hoffman** [comment]
Fixed in 2708034

See https://www.reddit.com/r/SigmaFileManager/comments/1463tie/sigma_file_manager_v17_progress_preview_image/
