### ISSUE TITLE
Drag & drop into address bar

### ISSUE THREAD

**Issue by logan478** [aleksey-hoffman/sigma-file-manager#232]
**Feature request:**

Hello, i think it would be amazing if there was drag & drop files or directory into address bar. You don´t need to leave your current directory in order to move files/directory.
Now you need to select files for move and go to directory where you want to put them. This would save that time. Thank you for considering.

**Comment by aleksey-hoffman** [comment]
That's a good idea, mate, I'm going to implement that

**Comment by aleksey-hoffman** [comment]
Added in [cf71fef](https://github.com/aleksey-hoffman/sigma-file-manager/commit/cf71fef54949260f966fb4acf7fb87702b3b2527)

Will be available in the next update (tomorrow)

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/61761672/5f9bc1c9-d785-41a7-8566-f5bd11b95c2f)
