### ISSUE TITLE
Can't download videos using the build-in Download Manager

### ISSUE THREAD

**Issue by Salted-Bread** [aleksey-hoffman/sigma-file-manager#237]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Trying to download videos by dragging them onto the app causes an error.

> Download failed
Error: Command failed: "C:\Users\(Username)\AppData\Roaming\Sigma file manager\app storage\bin\yt-dlp\yt-dlp.exe" --ffmpeg-location "C:\Users\(Username)\AppData\Roaming\Sigma file manager\app storage\bin\ffmpeg\bin\ffmpeg.exe" -f bestaudio -o "C:\Users\(Username)\Videos\%(title)s.%(ext)s" "https://www.youtube.com/watch?v=LDU_Txk06tM" ERROR: [youtube] LDU_Txk06tM: Unable to extract uploader id; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

### Steps to reproduce

1.  Drag a YouTube video onto App

### Environment

- OS: Windows 11
- App version: 1.6.0

**Comment by aleksey-hoffman** [comment]
Thanks, will fix it in the next update

**Comment by aleksey-hoffman** [comment]
Fixed in v1.7 (unreleased yet) [1d68a8e](https://github.com/aleksey-hoffman/sigma-file-manager/commit/1d68a8ed7931361a0c8ebf604cbec3b00c697b4c)
