### ISSUE TITLE
Drag items between tabs

### ISSUE THREAD

**Issue by RunicLena** [aleksey-hoffman/sigma-file-manager#243]
## Feature request:
Speaks for itself, really. Moving items far away is (to my knowledge) impossible at the moment. Maybe open the tab's directory when you roll over it with an item, much like windows 11's tabs?

**Comment by aleksey-hoffman** [comment]
Good first issue!

I like the suggestion. I was thinking about things to add to the next update. I'm going to implement it right now. 

The next update comes out tomorrow

**Comment by aleksey-hoffman** [comment]
Added in [cf71fef](https://github.com/aleksey-hoffman/sigma-file-manager/commit/cf71fef54949260f966fb4acf7fb87702b3b2527)

Will be available in the next update

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/61761672/f80a4653-2462-4652-9f59-e179902d291e)
