### ISSUE TITLE
"new" something label hidden behind blur

### ISSUE THREAD

**Issue by Rajdave69** [aleksey-hoffman/sigma-file-manager#255]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/86198810/51c73314-22d0-499e-a0a9-b9e240d1f266)
![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/86198810/adcbcec1-5e0f-49ab-8c5b-c1788949ffff)

The plus icon in the top left has a label which can not be read by hovering since it's shown behind the blur.

### Steps to reproduce

1. Install the app
2. go to navigator, hover over the plus icon

### Environment

- OS: Windows 11 
- App version: Latest

**Comment by aleksey-hoffman** [comment]
Thanks for the report!

**Comment by aleksey-hoffman** [comment]
Let's see if I can fix it for the next update

**Comment by aleksey-hoffman** [comment]
Fixed in 826f1ef

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/61761672/081bd867-f6a5-450a-bf7c-e46001618272)
