### ISSUE TITLE
Dragging file to another application causes app to die

### ISSUE THREAD

**Issue by Rajdave69** [aleksey-hoffman/sigma-file-manager#259]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

Dragging any file to another application crashes it and you need to close it through task manager to make it function again

Recording of the issue: https://rajtech.me/share/2023-07-06-10-55-52.mp4

### Steps to reproduce

1. Select any file
2. drag it to another app

### Environment

- OS:Windows 11 build 22622.601
- App version: 1.7 (latest)

**Comment by aleksey-hoffman** [comment]
Thank you, I will take a look

**Comment by Rajdave69** [comment]
Nevermind, this was some sort of weird issue with my PC which broke dragging through every application. A restart fixed it.

**Comment by aleksey-hoffman** [comment]
@Rajdave69 good to know!
