### ISSUE TITLE
[Feature request] Make the numpad work with the shortcuts

### ISSUE THREAD

**Issue by jdhqLifes** [aleksey-hoffman/sigma-file-manager#27]
## Feature request:
Idk if this is intended, maybe not, but i would be cool if we can use the numpad to complement the shortcuts, i mean e.g. currently i can not use `Shift + 2` with the numpad's 2 key.

**Comment by aleksey-hoffman** [comment]
Maybe we should reserve numpad buttons for the future shortcuts? There will be a lot of other actions added in the future. 
This would also avoid duplication.
What do you think?

**Comment by jdhqLifes** [comment]
> Maybe we should reserve numpad buttons for the future shortcuts? There will be a lot of other actions added in the future.
> This would also avoid duplication.
> What do you think?

yeah, sounds great, and the fact that user can re-assignate the shortcuts is great always, thanks for response

**Comment by aleksey-hoffman** [comment]
Okay, closing it for now.
I will add the ability to change app local shortcuts in a future update
Thanks
