### ISSUE TITLE
Marker icon like 

### ISSUE THREAD

**Issue by hoprikoma** [aleksey-hoffman/sigma-file-manager#280]
## Feature request:
Marker icon like in the picture, mark windows file for priority or anything else by setting a color badge next to folder or anything like this

![image](https://github.com/aleksey-hoffman/sigma-file-manager/assets/43370494/b8b2ab62-0a9f-418d-9651-2912a87caf48)

**Comment by aleksey-hoffman** [comment]
Hi, thanks for the suggestion. This feature is already in development

**Comment by hoprikoma** [comment]
Okay thank you :D
