### ISSUE TITLE
[Feature request] single-click directory navigation

### ISSUE THREAD

**Issue by aleksey-hoffman** [aleksey-hoffman/sigma-file-manager#30]
## Feature request:

Note to self: add an option to open navigator items with a single click

**Comment by jdhqLifes** [comment]
i thought you were the only developer behind this awesome project lol

**Comment by OfficialEsco** [comment]
> i thought you were the only developer behind this awesome project lol

Most likely a reminder from comments on Reddit https://www.reddit.com/r/Windows10/comments/nkoc3r/sigma_file_manager_app_is_released/gzebgt9/?context=3

tbh i was also trying to single click the first time i opened Sigma 🙄

**Comment by jdhqLifes** [comment]
> tbh i was also trying to single click the first time i opened Sigma 🙄

me too, kind of weird first time i saw it

**Comment by aleksey-hoffman** [comment]
@jdhqLifes yes currently I'm the only developer. I just added it for myself 😄 Not sure what's the best way to track all the issues.
I created a discussion where I will be storing all the "Improvements in development"

**Comment by aleksey-hoffman** [comment]
@OfficialEsco @jdhqLifes alright guys, it's settled then, I will add the feature in the next update, most likely tomorrow (merge it with other bug fixes)

**Comment by aleksey-hoffman** [comment]
@OfficialEsco great! Choice is always good. 
I added the ability to select an item without opening it when you press `Alt + Click` to see its properties.

Do you like the implementation? Would you change anything about it?

**Comment by Ansh4011** [comment]
> @OfficialEsco great! Choice is always good.
> I added the ability to select an item without opening it when you press `Alt + Click` to see its properties.
> 
> Do you like the implementation? Would you change anything about it?

I just tried this feature! Nice one! Makes it smoother and better! I guess no change needed!
