### ISSUE TITLE
questions 

### ISSUE THREAD

**Issue by fabiorug** [aleksey-hoffman/sigma-file-manager#316]

**Comment by fabiorug** [comment]
Is damaging to ADS people? Orizzonte scuola made an article. Is your program safe to use?

**Comment by fabiorug** [comment]
Is a program safe to use?

**Comment by aleksey-hoffman** [comment]
Hi 👋
Can you please explain what you mean?
The app is in general safe to use. It doesn't send any user data anywhere.

**Comment by aleksey-hoffman** [comment]
@antermin Thanks mate
