### ISSUE TITLE
[Problem report] Rename pop up titled WAS & NOW is reversed

### ISSUE THREAD

**Issue by jdhqLifes** [aleksey-hoffman/sigma-file-manager#32]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `Windows 10 x64` 

## Problem:
When i rename a file, the little pop-up in the right-bottom corner is showing the WAS and NOW title of the file in the opposite way, reversed.

![image](https://user-images.githubusercontent.com/67289912/119569776-d3129b00-bd74-11eb-97b8-f153fe88289a.png)

Here WAS title should be NOW title and viceversa.

**Comment by aleksey-hoffman** [comment]
Thanks, will fix it in the next update as well
