### ISSUE TITLE
[Problem Report] File date not reſpecting uſer ſetting

### ISSUE THREAD

**Issue by Alice196498** [aleksey-hoffman/sigma-file-manager#33]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: ` x64 | Windows 10` 

## Problem:
The date is diſplayed in the *Day Month Year* format irreſpective of the uſer’s ſettings in the Operating Syſtem, which can be confuſing to the uſer, or awkwardly diſplayed. I’d recommend either following the ſetting defined by the OS, or a ſetting in the application for the uſer to define the date format they wiſh to uſe.

**Comment by aleksey-hoffman** [comment]
Thanks for the reminder. I will fix this soon

**Comment by aleksey-hoffman** [comment]
Added in 05d1786 . Will be released in v1.4 update.

Time stat will now be displayed next to the date stat:

![image](https://user-images.githubusercontent.com/61761672/131233993-7aa89071-3f33-4ad2-9f9e-547c8f79a0ca.png)

Also added new setting to control month display format 8401af7:

### Setting date / time month format "numeric" (default):

**USA**: 5/23/2021, 11:16 PM
**Japan**: 2021/5/23 23:16
**Russia**: 23.05.2021, 23:16
**Germany** 23.5.2021, 23:16

### Setting date / time month format "short":

**USA**: May 23, 2021, 11:16 PM
**Japan**: 2021年5月23日 23:16
**Russia**: 23 мая 2021 г., 23:16
**Germany** 23. Mai 2021, 23:16

![image](https://user-images.githubusercontent.com/61761672/131233883-f8acd0a2-9cf1-4fd7-981d-c4834d386cf9.png)

**Comment by aleksey-hoffman** [comment]
Added in 05d1786 . Will be released in v1.4 update.

- Time will now be displayed alongside the date
- Both date and time will now be displayed in OS locale format.

Example: Japanese locale:

![image](https://user-images.githubusercontent.com/61761672/131234063-a42f25ba-9163-41e6-a13f-69d78610d594.png)

Also added new setting to control month display format 8401af7:

### Setting date / time month format "numeric" (default):

**USA**: 5/23/2021, 11:16 PM
**Japan**: 2021/5/23 23:16
**Russia**: 23.05.2021, 23:16
**Germany** 23.5.2021, 23:16

### Setting date / time month format "short":

**USA**: May 23, 2021, 11:16 PM
**Japan**: 2021年5月23日 23:16
**Russia**: 23 мая 2021 г., 23:16
**Germany** 23. Mai 2021, 23:16

![image](https://user-images.githubusercontent.com/61761672/131233883-f8acd0a2-9cf1-4fd7-981d-c4834d386cf9.png)
