### ISSUE TITLE
[Problem report] Non-ASCII characters in drive name not diſplayed properly

### ISSUE THREAD

**Issue by Alice196498** [aleksey-hoffman/sigma-file-manager#34]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: ` x64 | Windows 10` 

## Problem:
On the Home Page or hover text for a drive, if the name contains non-ASCII characters, the non-ſupported character(s) will be diſplayed as mojibake or queſtion marks.

**Comment by aleksey-hoffman** [comment]
Thank you for the report, I will try to fix it in the next update
