### ISSUE TITLE
Sigma file manager removed majority of my files 

### ISSUE THREAD

**Issue by redhed100** [aleksey-hoffman/sigma-file-manager#348]
### Problem description

I deleted files that I really needed on my extra disk D:. The files were deleted everywhere, even in folders that I had not accessed. I didn't confirm any deletion and was just checking the program functions.

### Steps to reproduce

1. Began to learn the functions of the program
2. Started global search
3. canceled the global search
4. Calculated the size of some folders
5. Looked in explorer and noticed that many files that I really needed had been deleted

### Operating system

windows 11

### App version

v2

**Comment by aleksey-hoffman** [comment]
Sorry that happened mate. It's strange that it did, since it can only call delete functions when you press `delete` button (from ui or keyboard), nothing else triggers those functions.

Try to use some data recovery software. It ususally restores most of the files

**Comment by redhed100** [comment]
I'm already doing data recovery, hopefully it will recover all the files I need
