### ISSUE TITLE
[Feature request] Possible light mode or higher dark mode contrast?

### ISSUE THREAD

**Issue by MrMAXVW** [aleksey-hoffman/sigma-file-manager#37]
I found out the texts are pretty difficult to read with the greyish white text and dark blueish background.
Is it possible to have a light mode, or custom appearance, or whiter texts?

**Comment by jczanfona** [comment]
I'm agree, same as https://github.com/aleksey-hoffman/sigma-file-manager/issues/62

**Comment by aleksey-hoffman** [comment]
I will add a higher contrast mode in one of the future updates. 
Maybe add an option to specify custom colors as well

**Comment by subframe7536** [comment]
switch modes in sync with the system will might be better

**Comment by aleksey-hoffman** [comment]
@subframe7536 I added a "light theme" filter in v1.5 update (unreleased). This is not a proper light theme, it's something in-between.

When I add a proper light theme, I will also add a setting to auto switch theme according to the system settings

## "Light theme" filter
![image](https://user-images.githubusercontent.com/61761672/146371768-76e04544-7e2a-4872-8380-27fc98f27e55.png)

**Comment by subframe7536** [comment]
GJ! Waiting for v1.5 release

**Comment by aleksey-hoffman** [comment]
Added in 273ff8c
The 1.5 version will be released tomorrow
