### ISSUE TITLE
[Problem report] Move selected to another directory not working as expected

### ISSUE THREAD

**Issue by OfficialEsco** [aleksey-hoffman/sigma-file-manager#4]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `Win10 Pro 21H1 19043.985` 

## Problem:
I was about to update my Win10 USB stick so i wanted to move my folder with some files to another location.
First issue is that it CAN'T move any Folders.
Second issue is that files don't get Cut and Pasted, they get Copied and Pasted.

**Comment by jdhqLifes** [comment]
same here pal :((

**Comment by aleksey-hoffman** [comment]
Thanks for the report. I already fixed it guys:
https://github.com/aleksey-hoffman/sigma-file-manager/commit/d1c30197fe73bf49b2b63c84ccee8cd043e808a1

The update is coming out in the next ~30 minutes. I'm having some troubles building Linux binary

**Comment by aleksey-hoffman** [comment]
Oh wait, I only fixed one of the problems you mentioned. 
I'm gonna fix the other one now as well

**Comment by aleksey-hoffman** [comment]
Guys, `v1.1.0` update is out. Please check if this issue is resolved for you

**Comment by OfficialEsco** [comment]
Yup problem solved 👍
