### ISSUE TITLE
[Problem report] Forced Startup

### ISSUE THREAD

**Issue by OfficialEsco** [aleksey-hoffman/sigma-file-manager#42]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `x64 Win10 Pro 21H1 19043.985` 

## Problem:
Every time you open Sigma it will force the startup to enabled

**Comment by OfficialEsco** [comment]
Bug still present in v1.1.0

**Comment by aleksey-hoffman** [comment]
fixed https://github.com/aleksey-hoffman/sigma-file-manager/commit/b018abc137c0c1fbc512c3446d7588569262ce61
