### ISSUE TITLE
Easy Open with "Program" Menu

### ISSUE THREAD

**Issue by itsmeshibintmz** [aleksey-hoffman/sigma-file-manager#44]
![image](https://user-images.githubusercontent.com/52344717/119665215-c87a0380-be51-11eb-9f51-2a81fcc3c8f2.png)

Open with a specific Program Menu is not that User Friendly. Please consider making it easier to pick up Installed Programs and Remember them for next time Use.

**Comment by aleksey-hoffman** [comment]
Thanks
Why do you think it's not user friendly? What can be improved?
I will soon add the function to automatically add installed programs to the list

**Comment by itsmeshibintmz** [comment]
> Why do you think it's not user friendly? What can be improved?
The Concept is cool but a little messy. For example, when I add VLC to play videos to the list, if I tick Program can open directories too, how will it be okay?

> I will soon add the function to automatically add installed programs to the list
That's great. Once again thank you for your amazing work.
