### ISSUE TITLE
 [Problem report] Drives not showing up in search even though i can navigate files

### ISSUE THREAD

**Issue by Zakaria-ouertani** [aleksey-hoffman/sigma-file-manager#48]
Error: Error: EISDIR, The device is not ready.
   'D:/'
      at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async o.mounted (app://./index.bundle.js:1:22620)
![Screenshot (56)](https://user-images.githubusercontent.com/75418838/119723290-324fd880-be65-11eb-89fc-84032a19b59c.png)

-There's also a notification saying: No drives selected.

**Comment by aleksey-hoffman** [comment]
Thanks, the problem is already fixed.
I will publish an update today / tomorrow

**Comment by Zakaria-ouertani** [comment]
> Thanks, the problem is already fixed.
> I will publish an update today / tomorrow

Thanks
