### ISSUE TITLE
[Feature Request] Label drive letter on Drive Quickaccess buttons when sidebar is minimised

### ISSUE THREAD

**Issue by sfchang92** [aleksey-hoffman/sigma-file-manager#5]
## Feature request:

QOL improvement to add drive letter to the drive Quickaccess buttons when sidebar is minimised.

![image](https://user-images.githubusercontent.com/14126605/119505925-04ed2700-bda0-11eb-9a22-328409087121.png)

**Comment by aleksey-hoffman** [comment]
Thanks for the suggestion

It already shows all the information when you hover the cursor over it. 
I think adding letters would clutter the interface, unnecessarily.

**Comment by aleksey-hoffman** [comment]
Hi,
I added a setting for this in v1.5, I'm planning to release it in June, Stay tuned :)

![image](https://user-images.githubusercontent.com/61761672/169570456-312da224-933a-4806-9570-e9e6fb863ac1.png)
