### ISSUE TITLE
[Problem Report] Error on launch

### ISSUE THREAD

**Issue by WolvenSpectre** [aleksey-hoffman/sigma-file-manager#50]
## System info:
- **App version**: `Sigma 1.00` 
- **Operating System**: `Win10Pro x64` 

## Problem:Launching Program opens error window/ No drives detected

Error: Error: EISDIR, The device is not ready.
 'X:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

https://i.imgur.com/sjRXvdU.png

Drive Management: https://i.imgur.com/CZR2Bct.png

Computer:      BIOSTAR Group A960D+
CPU:           AMD FX-8370 (Piledriver/Vishera, OR-C0 (Orochi))
               4000 MHz (20.00x200.0) @ 4000 MHz (20.00x200.0)
Motherboard:   BIOSTAR Group A960D+
BIOS:          080015, 09/04/2014
Chipset:       SB750/SB710
Memory:        16384 MBytes @ 800 MHz, 11-11-11-28
               - 8192 MB PC14200 DDR3 SDRAM - Atermiter
               - 8192 MB PC14200 DDR3 SDRAM - Atermiter
Graphics:      GIGABYTE GeForce GTX 960 OC 4GB
               NVIDIA GeForce GTX 960, 4096 MB GDDR5 SDRAM
Drive:         TOSHIBA DT01ACA200, 1953.5 GB, Serial ATA 6Gb/s @ 3Gb/s
Drive:         ADATA SP550, 234.4 GB, Serial ATA 6Gb/s @ 3Gb/s
Drive:         TOSHIBA DT01ACA200, 1953.5 GB, Serial ATA 6Gb/s @ 3Gb/s
Drive:         PIONEER BD-RW   BDR-209D, BD-RE
Sound:         ATI/AMD SB600 - High Definition Audio Controller
Sound:         NVIDIA GM206 - High Definition Audio Controller
Network:       RealTek Semiconductor RTL8168/8111 PCI-E Gigabit Ethernet NIC
OS:            Microsoft Windows 10 Professional (x64) Build 19043.985

**Comment by leorossi2005** [comment]
This problem has already been reported here #1 , I also have this problem and from what I understand it will be solved in the 1.0.X update.

**Comment by aleksey-hoffman** [comment]
Thank you for the report, the problem is already fixed.
I will publish an update today / tomorrow
