### ISSUE TITLE
[Problem Report] Immediate error after install - "The device is not ready. 'D:/'"

### ISSUE THREAD

**Issue by chillinglucifer** [aleksey-hoffman/sigma-file-manager#54]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `Windows 10 Professional x64 Version 21H1 (OS Build 19043.985)` 

## Problem:

App immediately told me to report this, so here I am!

`Error: Error: EISDIR, The device is not ready.
 'D:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)`

**Comment by aleksey-hoffman** [comment]
Thank you for the report, the problem is already fixed.
I will publish v1.1.0 update in the next 1-2 hours
