### ISSUE TITLE
[Feature request] Support for cloud storage drives

### ISSUE THREAD

**Issue by eldark** [aleksey-hoffman/sigma-file-manager#57]
There are several third-party applications that allow you to "mount" cloud storage accounts (Dropbox, MEGA, Google Drive, etc) as if they were local or network drives. This feature request is to have support for this kind of usage.

**Comment by brayjamin** [comment]
This should already work, if I'm not mistaken. OneDrive and Dropbox's folders, for example, are both treated as normal folders in Windows 10. Therefore they should still be viewable in Sigma.. However, I don't think we're going to be getting the file status icons like in explorer...
![image](https://user-images.githubusercontent.com/23380792/120260747-7c213000-c264-11eb-9df6-da4cc7cf5e77.png)

**Comment by aleksey-hoffman** [comment]
It might be possible to implement it similarly to the default file managers, with statuses and everything. 
I'll have to research this.

**Comment by aleksey-hoffman** [comment]
Fixed in 574787c
Will be released in v1.4 (on Saturday)

**Comment by aleksey-hoffman** [comment]
OneDrive was added in 574787c
Google Drive mounts a virtual drive and works similarly to any other drive,
Will be released in v1.4 (on Saturday)

## Home page

OneDrive card will be displayed on the drive list and navigation panel

![image](https://user-images.githubusercontent.com/61761672/131690218-495c6c69-1f26-47de-92c6-a286a9a8f895.png)

## Navigator

Offline status will be displayed on the item card if the file is offline (size on disk is 0)

![image](https://user-images.githubusercontent.com/61761672/131690515-dbc2148e-3e7d-4e73-89df-3e66cce3d8e3.png)

**Comment by aleksey-hoffman** [comment]
> However, I don't think we're going to be getting the file status icons like in explorer...

@brayjamin you are definitely getting them. Both the status icon and the description in the header of the info panel

![image](https://user-images.githubusercontent.com/61761672/131873664-878b26d4-136e-4cbd-ae81-4f1fd0a78c09.png)
