### ISSUE TITLE
Hidden files/folders

### ISSUE THREAD

**Issue by andersberglund** [aleksey-hoffman/sigma-file-manager#6]
## Feature request: 
A checkbox for show or hide hidden files/folders as in Window file explorer.

**Comment by mattm-malone** [comment]
Would also like to see this. I have something working on my fork, just need to create ui for it. Do we want it in the filter menu like so?
![image](https://user-images.githubusercontent.com/31638037/119742586-a4311d80-be77-11eb-9605-fe181622d045.png)

Or somewhere in the settings menu? Let me know what you have in mind @aleksey-hoffman
