### ISSUE TITLE
Option to disable reassertion of auto-runs when manually disabled.

### ISSUE THREAD

**Issue by WolvenSpectre** [aleksey-hoffman/sigma-file-manager#61]
## Feature request: 
If you choose to disable the Auto-Run for Sigma on Windows, the next time you launch it it reasserts an auto-run leading to redundant Auto-Run entries.  An Option to disable this behavior and/or temporarily disable it (especially during early testing of the software) would be great for those of us who only want to test it part time or already have large list of Auto-Run features loading at log in.

**Comment by aleksey-hoffman** [comment]
Fixed in b018abc
