### ISSUE TITLE
Double click delay issue

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#63]
## Problem: 
When I change the double click delay (in the general settings tab extreme bottom) to 100ms, it turns out that I can't go to any directory(in short no response by double click)! Is it so that the delay is stable at one point or something?
You can also refer to the image below! Thanks!
![image](https://user-images.githubusercontent.com/84930340/119943306-7e5b6400-bfb0-11eb-848b-faf0b8e0411d.png)

**Comment by aleksey-hoffman** [comment]
Perhaps `100 ms` is just not enough time for you to click it the 2nd time, I think I will limit the delay to the range of `200 - 1000 ms`

**Comment by Ansh4011** [comment]
Oh! Thanks😀

**Comment by aleksey-hoffman** [comment]
Fixed in 27c7570
