### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#65]
## Feature request: 
I know tabs option is there! But can the tab be displayed as in browser like in the reference picture! This feature can be taken for future but is worth! It will make the navigation really easier! 
![image](https://user-images.githubusercontent.com/84930340/119944321-c038da00-bfb1-11eb-8ade-9e2bc6f8bb00.png)

**Comment by aleksey-hoffman** [comment]
Thanks for the suggestion. 
It's already planned for a future release. I will add an option to switch to this tab variation

**Comment by Ansh4011** [comment]
Seems Cool!

**Comment by jczanfona** [comment]
Please it's a _must_ option...
Tx a lot for this sw !!!

**Comment by jczanfona** [comment]
PLS add this to the v1.3.0 milestone

**Comment by aleksey-hoffman** [comment]
@jczanfona I don't think I can develop this feature by v1.3. Currently I don't have enough funding for the project, so I can only dedicate about 2 hours / day working on it, which means I have to postpone some features until next releases.

**Comment by jczanfona** [comment]
Don't worry, I know what you mean...
Thanks for the effort!

**Comment by aleksey-hoffman** [comment]
Added in b021aee
Will be released in v1.5 (tomorrow)
