### ISSUE TITLE
[Problem report] Duplicate Process

### ISSUE THREAD

**Issue by OfficialEsco** [aleksey-hoffman/sigma-file-manager#7]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `Win10 Pro 21H1 19043.985` 

## Problem:
Everytime you open Sigma it makes a new process instead of opening the previous one
![image](https://user-images.githubusercontent.com/15158490/119507261-fa666980-bd6e-11eb-88f5-7f099e39d0d6.png)
![image](https://user-images.githubusercontent.com/15158490/119507316-06eac200-bd6f-11eb-8213-dd7836cb00d0.png)

It happens on both "Minimize to tray and keep in memory" and "Minimize to tray and minimize memory usage"
![image](https://user-images.githubusercontent.com/15158490/119509201-b83e2780-bd70-11eb-82f7-7576aeb19b20.png)

**Comment by aleksey-hoffman** [comment]
Oh wow, you tested like half the app already :)
Thank you for the help.

**Comment by aleksey-hoffman** [comment]
How are you closing the app? I have the same settings. When I click on the window close button, it completely closes the app.
Is it possible that those processes are created by the error window or something like that, or do see them being created when you close / open the app?

**Comment by aleksey-hoffman** [comment]
What action causes these processes to duplicate? 
I tried all 3 settings:
- 1st one does not affect the processes at all
- 2nd closes the main process and creates it when you re-open the app.
- 3rd closes all processes and exists

Is it possible that those processes are created by the error window or something like that or do you see them being created when you close / open the app?

**Comment by OfficialEsco** [comment]
> What action causes these processes to duplicate?
> I tried all 3 settings:
> 
> * 1st one does not affect the processes at all
> * 2nd closes the main process and creates it when you re-open the app.
> * 3rd closes all processes and exists
> 
> Is it possible that those processes are created by the error window or something like that or do you see them being created when you close / open the app?

This is on my main system where there is no error messages, the duplicates appears just by closing and opening the app

**Comment by OfficialEsco** [comment]
Bug still present in v1.1.0

**Comment by Ansh4011** [comment]
> Bug still present in v1.1.0

Hey buddy! I just realized that this feature is meant to use it instantly(or keep the app in memory), like as the first option in 'Window Controls' says if you close it then you are supposed to open it via system tray or else it will open more processes and more and more and as it is supposed to be kept in tray so it won't close, and for what you are asking, select the 3rd option 'Close the App Completely', it will solve your purpose most probably. Have a look at the video!

https://user-images.githubusercontent.com/84930340/120059848-b4ace800-c071-11eb-97f1-0dbd7039b6ec.mp4

**Comment by OfficialEsco** [comment]
@Ansh4011 just because that is how it works at the moment does not mean thats how its supposed to be.
There is a main process and a sub process, Sigma opens multiple of the Main Process which does all the heavy lifting.
Sigma is also meant to be used with Workspaces/Tabs not multiple windows.

**Comment by Ansh4011** [comment]
> @Ansh4011 just because that is how it works at the moment does not mean thats how its supposed to be.
> There is a main process and a sub process, Sigma opens multiple of the Main Process which does all the heavy lifting.
> Sigma is also meant to be used with Workspaces/Tabs not multiple windows.

I agree with you! I just shared that this is how it works at the moment! And the main process multiplies when we start it via .exe though the software is meant to be opened via system tray for the first two options in 'Window Controls'! Anyways we got a solution to your problem, just go with 'Close the app Completely' option to avoid multiple processes and to open it via .exe as well!
*This is just what I opine and I would love to be corrected! Thanks!

**Comment by aleksey-hoffman** [comment]
@OfficialEsco wait a second. I think I know why I haven't been able to reproduce this bug. 
Have you been re-opening the app from the shortcut / task bar, creating a new instance of the app?

Does it work properly if you re-open it using global shortcut `CTRL + SHIFT + SPACE` or from the tray icon?

If that's the case, I will prevent the ability to open multiple app instance and the bug is fixed

**Comment by Ansh4011** [comment]
> @OfficialEsco wait a second. I think I know why I haven't been able to reproduce this bug.
> Have you been re-opening the app from the shortcut / task bar, creating a new instance of the app every time?
> 
> Does it work properly if you re-open it using global shortcut `CTRL + SHIFT + SPACE` or from the tray icon?
> 
> If that's the case, I will prevent the ability to open multiple app instance and the bug is fixed

Yupp..... When we open it via tray icon, it has no issues

**Comment by OfficialEsco** [comment]
> Have you been re-opening the app from the shortcut / task bar, creating a new instance of the app every time?
> 
> Does it work properly if you re-open it using global shortcut `CTRL + SHIFT + SPACE` or from the tray icon?
> 
> If that's the case, I will prevent the ability to open multiple app instance and the bug is fixed

Yes, that is what most people will do which is why creating a new instance is a dumb idea, you need to make it so there is one main instance which stays in the tray bar and then make a sub instance which only opens the Sigma Windows.

If you add horizontal tabs like someone requested it could open in another tab instead of opening a new Window.

**Comment by Ansh4011** [comment]
> > Have you been re-opening the app from the shortcut / task bar, creating a new instance of the app every time?
> > Does it work properly if you re-open it using global shortcut `CTRL + SHIFT + SPACE` or from the tray icon?
> > If that's the case, I will prevent the ability to open multiple app instance and the bug is fixed
> 
> Yes, that is what most people will do which is why creating a new instance is a dumb idea, you need to make it so there is one main instance which stays in the tray bar and then make a sub instance which only opens the Sigma Windows.
> 
> If you add horizontal tabs like someone requested it could open in another tab instead of opening a new Window.

True! I agree with you!
