### ISSUE TITLE
Problem with Banner

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#76]
## Problem: 
When I Hide the banner from the media banner options and restart the application, the banner appears again!

https://user-images.githubusercontent.com/84930340/120004200-1e86ac80-bff4-11eb-844f-0eaca3888a09.mp4

**Comment by aleksey-hoffman** [comment]
Thanks for the demonstration.
It's a known issue. I will fix it in the next update

**Comment by Ansh4011** [comment]
Thanks😁

**Comment by aleksey-hoffman** [comment]
Fixed in 73cdc75
