### ISSUE TITLE
Force Autostart 

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#77]
## Problem: 
It starts itself every time we boot in.... I have tried disabling the task from task manager, but once we open SFM again, it itself gets enabled! Also I have tried the killing the startup process by deleting it manually in the registry via autorun, but it again created another task!

**Comment by adilsoncasula** [comment]
I'm agree with this.

**Comment by aleksey-hoffman** [comment]
Thanks for the report.
I fixed the issue and will include it into the next update

**Comment by Ansh4011** [comment]
Thanks a lot for this update😀

**Comment by aleksey-hoffman** [comment]
Fixed in b018abc
