### ISSUE TITLE
Extract Folder

### ISSUE THREAD

**Issue by AgentDobby** [aleksey-hoffman/sigma-file-manager#80]
I see a Compress top Zip option when right clicking. Im not too sure if this has been mentioned yet but an Extract Folder option would be nice.

**Comment by Ansh4011** [comment]
It do exists in the context menu(right click) itself! The option says 'Extract Archive' and supports tar, zip, and 7z format !

![image](https://user-images.githubusercontent.com/84930340/120060080-3bae9000-c073-11eb-903a-7db562b342cb.png)

**Comment by Ansh4011** [comment]
It do exists in the context menu(right click) itself! The option says 'Extract Archive' and supports tar, zip, and 7z format !

![image](https://user-images.githubusercontent.com/84930340/120060080-3bae9000-c073-11eb-903a-7db562b342cb.png)

**Comment by AgentDobby** [comment]
Ahh ok i see it now. I was trying it on iso's and rar.

**Comment by Ansh4011** [comment]
oh! Okay😀

**Comment by aleksey-hoffman** [comment]
The app supports ISO and RARs and a lot of other formats.

I will add support for other formats in the next update

### Supported formats:
- Packing / unpacking: 7z, XZ, BZIP2, GZIP, TAR, ZIP and WIM
- Unpacking only: AR, ARJ, CAB, CHM, CPIO, CramFS, DMG, EXT, FAT, GPT, HFS, IHEX, ISO, LZH, LZMA, MBR, MSI, NSIS, NTFS, QCOW2, RAR, RPM, SquashFS, UDF, UEFI, VDI, VHD, VMDK, WIM, XAR and Z.

**Comment by Ansh4011** [comment]
Hi @aleksey-hoffman, can you keep me as your assistant if you don't mind?😅

**Comment by AgentDobby** [comment]
Hmm well then thats odd because i dont get any option to extract from rar's or iso's, only zip folders. Even after closing the app and restarting it.  I could try and reinstalling the app but im pretty sure that wont really fix anything.

**Comment by aleksey-hoffman** [comment]
@AgentDobby I will add support for other formats in the next update. The formats I mentioned are supported but they don't work in the app yet

**Comment by aleksey-hoffman** [comment]
@Ansh4011 what do you mean by assistant, mate?
You're already helping out by testing the app and reporting things, so practically you are already an assistant :)

**Comment by Ansh4011** [comment]
> @Ansh4011 what do you mean by assistant, mate?
> You're already helping out by testing the app and reporting things, so practically you are already an assistant :)

OH! Thanks a lot buddy😀

**Comment by aleksey-hoffman** [comment]
If you guys see a dinosaur in the app, pet him on the head, he will show you something interesting :)

**Comment by Ansh4011** [comment]
> If you guys see a dinosaur in the app, pet him on the head, he will show you something interesting :)
You surprised me😃😉! That is too good! I am in love with the file manager! One of it's own kind! Salute and Appreciations to you buddy!

![image](https://user-images.githubusercontent.com/84930340/120065797-dec1d280-c090-11eb-82f1-6cc2198e70bd.png)

**Comment by aleksey-hoffman** [comment]
@Ansh4011 hehe :) glad you liked it.

**Comment by Ansh4011** [comment]
> @Ansh4011 hehe :) glad you liked it.
> 🤐

😃👌✌

**Comment by Ansh4011** [comment]
HI @aleksey-hoffman, Just asking for curiosity, please don't rush after reading my comment, and take your time! So, by when is the next version supposed to come? Too curious😅! Thanks!

**Comment by aleksey-hoffman** [comment]
Fixed in 774bbcf
