### ISSUE TITLE
[Feature Request] refresh button

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#81]
## Feature request: 
Can we get a refresh/reload directory option in the context menu! It would really helpful as this is the most used feature for many! Thanks!

**Comment by aleksey-hoffman** [comment]
The refresh button is located in the toolbar

![image](https://user-images.githubusercontent.com/61761672/120066013-16bf1a80-c07d-11eb-9e71-452101fc8435.png)

**Comment by Ansh4011** [comment]
> The refresh button is located in the toolbar
> 
> ![image](https://user-images.githubusercontent.com/61761672/120066013-16bf1a80-c07d-11eb-9e71-452101fc8435.png)

Yeah it is there indeed! but like several times we have to work with files which are at the bottom so this functionality is pretty kinda necessary as what I opine and ofcourse the old right click habit! Actually I was working with some files and extracted a file and so to see it I had to refresh it!

**Comment by Ansh4011** [comment]
Or we can get a shortcut mapped for it!

**Comment by aleksey-hoffman** [comment]
I will add the F5 shortcut for it.
I don't think it should be in the context menu though. If we add everything in the menu, it would get cluttered very quickly.

**Comment by Ansh4011** [comment]
> I will add the F5 shortcut for it.
> I don't think it should be in the context menu though. If we add everything in the menu, it would get cluttered very quickly.

Totally Agreed! F5 functionality would be nice! Thanks!

**Comment by Ansh4011** [comment]
btw, @aleksey-hoffman, are you on Discord?

**Comment by aleksey-hoffman** [comment]
Fixed in 4a26f11
