### ISSUE TITLE
Error when starting Sigma

### ISSUE THREAD

**Issue by swanserquack** [aleksey-hoffman/sigma-file-manager#94]
## Problem:
Whenever I attempt to start Sigma a get a Javascript error saying "A Javascript error occurred in the main process". The whole error can be seen in the image below (Name blurred out). Thanks in advance.
![Sigma Error](https://user-images.githubusercontent.com/75944176/120346515-58f19180-c2f3-11eb-9f19-e1db34bf49d9.png)

## System info:
- **App version**: `1.1.0`
- **Operating System**: `x64 Windows 10 21H1`

**Comment by Ansh4011** [comment]
You can try restarting your pc and then start Sigma File Manager! Or check your documents folder and its path as well! Sometimes there are old temp. files which get corrupt as well or even you may not have it's ownership causing the problem(try takeown in that case) , I too faced the same problem with some other software, but it got resolved as soon as I restarted! Maybe this could help you too!

**Comment by swanserquack** [comment]
> You can try restarting your pc and then start Sigma File Manager! Or check your documents folder and its path as well! Sometimes there are old temp. files which get corrupt as well or even you may not have it's ownership causing the problem(try takeown in that case) , I too faced the same problem with some other software, but it got resolved as soon as I restarted! Maybe this could help you too!

I have now restarted my PC with no change to the error. I have checked my documents path which is correct (C:\User\username\Documents) and I also checked the registry keys to make sure they have the right path for the documents folder (they did). I also checked my folder permissions (which were fine). I really have no idea whats going on.

**Comment by swanserquack** [comment]
After getting a new PC the file manager works fine now. I think the issue may be related to an earlier problem when the path to documents was messed to due to OneDrive sync and even with the right registry options in nothing changed. The manager is great, keep it up!

**Comment by aleksey-hoffman** [comment]
@swanserquack thank you for the information and for the feedback on the app. 
I have a lot of features planned, but unfortunately I wasn't able to spend much time working on the app due to the luck of funding. I think I might have to start promoting the app all over social media and attract sponsors to get enough funding for the development.

**Comment by aleksey-hoffman** [comment]
Fixed in 28766c1
